let lang = {
    en: {
        'History': 'HISTORY',
        'EthTransactions': 'ETH Transactions',
        'SentTransactions': 'SENT Transactions',
        'NoTransactions': 'No Transactions Yet',
        'Send': 'SEND',
        'To': 'To',
        'SendTo': 'SEND TO ADDRESS',
        'AmountTo': 'AMOUNT TO SEND',
        'TokenBal': 'TOKEN BALANCE',
        'Convert': 'CONVERT',
        'ConvertERC': 'Convert ERC20 to SENT',
        'ExchangeERC': 'Exchange ERC20 tokens for Sentinel tokens',
        'From': 'From',
        'Amount': 'Amount',
        'GasLimit': 'Gas Limit',
        'Password': 'Password',
        'GasPrice': 'Gas Price',
        'Next': 'NEXT',
        'Back': 'BACK',
        'Out': 'OUT',
        'In': 'IN',
        'Status': 'Status',
        'Success': 'Success',
        'Fail': 'Fail',
        'Copy': 'Copy',
        'City': 'City',
        'Country': 'Country',
        'Due': 'Due',
        'Copied': 'Copied to Clipboard Successfully',
        'Receive': 'RECEIVE',
        'GetTokens': 'GET FREE TOKENS',
        'VpnList': 'VPN LIST',
        'SelectNode': 'Select any node to connect',
        'CheckInternet': 'Check your internet connection',
        'NoVPN': 'No VPN Connected',
        'VpnHistory': 'VPN HISTORY',
        "TransactionsHistory": "TRANSACTIONS HISTORY",
        'TotalDue': 'Total Due',
        'TotalDuration': 'Total Duration',
        'TotalData': 'Total Received Data',
        'SessionId': 'Session ID',
        'Sessions': 'Sessions',
        'VpnAddress': 'VPN Address',
        'Bandwidth': 'Bandwidth',
        'Latency': 'Latency',
        'Loading': 'Loading...',
        'Speed': 'Speed',
        'Location': 'Location',
        'Duration': 'Duration',
        'DownloadUsage': 'Download Usage',
        'UploadUsage': 'Upload Usage',
        'Disconnect': 'Disconnect',
        'DisconnectVPN': 'Disconnected VPN',
        'ConnectedVPN': 'Connected VPN',
        'Disconnecting': 'Disconnecting...',
        'Connecting': 'Connecting...Please Wait',
        'ClickPay': 'Click to Pay',
        'ReceivedData': 'Received Data',
        'SearchCity': 'Search City or Country',
        'Time': 'Time',
        'NoServers': 'Currently, no VPN servers are available',
        'PayNow': 'Pay Now',
        'AlreadyReport': 'Already Paid? Report',
        'List': 'LIST',
        'VPNDetails': 'VPN Details',
        'ClickVPN': 'Click any node to connect to VPN',
        'KeystoreLogin': 'Enter Keystore Password to Login',
        'KeyPass': 'Enter keystore password',
        'CheckCre': 'Checking Credentials...',
        'Map': 'MAP',
        'Pay': 'Pay',
        'Flag': 'Flag',
        'Uhave': 'You have',
        'Close': 'Close',
        'Cancel': 'CANCEL',
        'Connect': 'CONNECT',
        'Submit': 'Submit',
        'TestMode': 'TEST MODE ACTIVATED',
        'AnonymousVPN': 'Anonymous VPN backed by blockchain security',
        'OpenSource': 'Open-source wallet and secure service platform',
        'CreateRestore': 'Create / Restore Wallet',
        'SentinelAnonymity': 'Sentinel Anonymity Platform',
        'PeerToPeer': 'Peer to peer erc based privacy application suite with multi chain for gas-free services and anonymous erc token transactions',
        'BetaVersion': 'Beta Version 0.1.0 with testnet',
        'InitialPayment': 'Initial Payment Reminder',
        'InorderVPN': 'Inorder to use VPN, you need to pay 100 sents for the first time. Please pay and then try to connect to the vpn.',
        'CreateAUID': 'Create your Anonymous User ID',
        'CreateTooltip': 'Enter a password and create your own Sentinel Anonymous User ID (AUID)',
        'PasswordAUID': 'Enter Password to create AUID',
        'ConfirmPwd': 'Confirm Password',
        'Create': 'Create',
        'SelectKeystore': 'Select keystore file',
        'RestoreKeystore': 'Restore Keystore File',
        'DidNotMatch': 'Password and Confirm Password did not match',
        'KeyPassMatch': 'Keystore and Password does not match',
        'BeCareful': 'Be Careful',
        'CopyKeys': "Copy your keys to some secured place. Remember we don't store any of your keys in ours databases. We don't maintain a database.",
        'YourAddress': 'Your Ethereum Wallet Address',
        'PrivateKey': 'Private Key',
        'KeyLocation': 'Your keystore file is stored at',
        'YesUnderstand': 'Yes, I understood, I saved my keys in a secure place',
        'GoToDash': 'Go to Dashboard',
        'AmountEmpty': 'Amount field is Empty',
        'PasswordEmpty': 'Password field is Empty',
        'ToTooltip': 'Wallet Address that you want to send Sentinel Tokens to',
        'AmountTool1': 'Total Ethereum/Sentinel Tokens that you want to send to.',
        'AmountTool2': 'Yes, this wallet can hold Ethereum too.',
        'GasFieldTool': '21000 is the default gas limit',
        'GasPriceTool': 'Amount you pay per unit of gas',
        'PasswordTool': 'Your Sentinel AUID Password',
        'Price': 'Price (SENTS/GB)',
        'Cost': 'Price',

        'WalletTM': 'TENDERMINT',
        'WalletERC': 'ERC20',
        'TSent': 'TSENT',
        'TestNet': 'TESTNET',
        'WalletAddress': 'WALLET ADDRESS',
        'ERC20WalletCopy': 'Copy ERC20 Sent Wallet Address',
        'TMWalletCopy': 'Copy Tendermint Wallet Address',
        'TestSent': 'TEST SENT',
        'Sent': 'SENT',
        'Eth': 'ETH',
        'TestEth': 'TEST ETH',
        'TestNetTM': 'TENDERMINT TESTNET',
        'TestNetETH': 'ETHEREUM TESTNET',
        'RefreshBalTM': 'Refresh TENDERMINT Balance ',
        'RefreshBalETH': 'Refresh ERC20 Balance ',
        'Sending': 'SENDING...',
        'TM': 'TENDERMINT',
        'ETH': 'ETHEREUM',
        'TxHistory': 'TX HISTORY',
        'Account': 'ACCOUNT',
        'Transfer': 'TRANSFER',
        'NoSentTx': 'No SENT Transactions Yet',
        'NoEthTx': 'No ETH Transactions Yet',
        'NodVPNNodes': 'No dVPN nodes found',
        'NoPrevSessions': 'No Previous Sessions',
        'ConnectTodVPN': 'Connect to dVPN',
        'ConnectingdVPN': "Connecting...",
        'Connected': 'Connected',
        'Activated': 'Activated',
        'TMTestNet': 'Tendermint Test Net',
        'ETHTestNet': 'Ethereum Test Net',
        'ETHMainNet': 'Ethereum Main Net',
        'Offline': 'You Are Offline',
        "OpenVPN": "OpenVPN",
        'Socks5': "SOCKS5",
        'Failed': 'Failed',
        'Sents': ' SENTS',
        'Secs': ' sec',
        'MS': " ms",
        'Mbps': ' Mbps',
        'SentPerGb': ' SENT/GB',
        'TSentLocked': 'TSENT Locked',
        'TSentConsumed': 'TSENT Consumed',
        'Note': 'Note: Your account balance is 0 TSENT. You can get some TSENTs for free, click on GET TOKENs above.',
        'TxFailed': 'Transaction Failed',
        'IncorrectPwd': 'Incorrect Password',
        'TxSuccess': 'Transaction done successfully',
        'VpnConnected': 'VPN Connected',
        'WentWrong': 'Something went wrong',
        'EnterTxHash': "Enter txhash of transaction",
        'ErrOccured': 'Error Occured',

        'Algorithm': 'Algorithm',
        'Version': 'Version',
        'Rating': 'Rating',
        'Public': 'Public',
        'Private': 'Private',
        'Selected': 'Selected',
        'OpenVPNList': 'OpenVPN List',
        'GWEI': ' GWEI',
        'Eths': ' ETHS',
        "Refresh": "Refresh",
        "Sentinel": "SENTINEL",

        "SearchdVPNnode": "Search for a dVPN node",
        "SwitchPrivate": "Switch To Private Network",
        "EnterAuthCode": "Please enter your Auth Code to connect to the Private Network",
        "AuthCode": "Auth Code",
        "ToggleMenu": "Toggle Menu",
        "WindowTitle": "Sentinel Network - dVPN - alpha-0.1.0",
        "RunInBackground": "Run in Background",
        "Confirm": "Confirm",
        "CurrentlyConnectedToVPN": "You are currently connected to a VPN",
        "DisconnectOpenVPN": "DisconnectOpenVPN",
        "Edit": "Edit",
        "Undo": "Undo",
        "Redo": "Redo",
        "Cut": "Cut",
        "Paste": "Paste",
        "SelectAll": "Select All",
        "Quit": "Quit",
        "ToggleDevTools": "Toggle Developer Tools",
        "IPAddress": "IP Address",
        "Upload": "Upload",
        "Download": "Download",
        "RateSession": "Rate this session",
        "Comment": "Comment",
        "RatedSuccess": "Rated Successfully",
        "ConnectedToVPN": "Connected to VPN",

        "MessageSuccess": "This is a success message!",
        "MessageErr": "This is an error message!",
        "MessageWarn": "This is a warning message!",
        "MessageInfo": "This is an information message!",
        "CheckStatus": "Check Status",
        "OR": "(OR)",
        "CreateWalletSST": "Create a Wallet on Sentinel Tendermint TestNet (STT) #1",
        "AccountName": "Account Name",
        "AccountPwd": "Account Password",
        "CreateAccount": "Create Account",
        "MB": "MB",
        "OfflineInFooter": "Offline",
        "TxID": "TxID",
        "SentGroup": "SentinelGroup.io",
        "SwapOnPIVX": "Swap on PIVX Tokens",
        "EnterRefundAddr": "Enter refund address",
        "EnterPIVXAddr": "Enter pivx address",
        "Example": "Example",
        "KeyStorePwd": "KEYSTORE PASSWORD",
        "PIVXTokensto": "PIVX Tokens to ",
        "Swap": "SWAP",
        "Swaping": "SWAPING",
        "Total": "Total",
        "TokensToBeSwapped": "tokens to be swapped",
        "Enter": "Enter",
        "RefundAddr": "refund Address",
        "PIVXAddr": "PIVX Address",
        "Expected": "Expected",
        "Tokens": " Tokens",
        "Sentinel[SENT]": "Sentinel [SENT]",
        "NoTokens": "No Tokens Found",
        "Address": "Address",
        "PubKey": "Public Key",
        "Seed": "Seed",
        "GoToSTWallet": "Go To Sentinel Tendermint Wallet",
        "NoVPNUsed": "No VPN Used",
        "ProblemEnablingPrivateNet": "Problem in enabling private net",
        "PrivateNetEnabledWith": "Private Net is Enabled with ",
        "SentTokens": "SENT TOKENS",
        "Balance": "Balance",
        "Converting": "CONVERTING",
        "OpenVpnNotInstalled": "OpenVPN Not Installed.",
        "PleaseGo": "Please go to",
        "OpenVpnPath": "C:\\Users\\(your-user-name)\\AppData\\Local\\Sentinel\\app-0.1.0\\resources\\extras",
        "OpenVpnInstallCmd": "and run openvpn-install-2.3.18-I602-x86_64.exe.",
        "OpenVpnMessage": "Just Install Openvpn without changing installation directory.",
        "YourUserName": "your-user-name",
        "AndRun": "and run",
        "OpenVpnInstallAlert": "OpenVPN Not Installed. Please go to C:\\Users\\(your-user-name)\\AppData\\Local\\Sentinel\\app-0.1.0\\resources\\extras and run openvpn-install-2.3.18-I602-x86_64.exe. Just Install Openvpn without changing installation directory.",
        "ConnectedSocks": "Connected to Socks",

        "Can'tdetectcurrentosplatform.": "Can't detect current os platform.",
        "ConnectingVPNFailed.PleaseTryAgain": "Connecting VPN Failed. Please Try Again",
        "Unabletoreachsentinelserveratthismoment": "Unable to reach sentinel server at this moment",
        "Currentlyserverhassomenetworkissues.Pleasetryotherserver.": "Currently server has some network issues.Please try other server.",
        "Somethingwentwrong.PleaseTryAgain": "Something went wrong.Please Try Again",
        "Erroroccuredwhileinstallingbrew": "Error occured while installing brew",
        "PackageBrewisnotInstalled": "Package Brew is not Installed",
        "Erroroccuredwhileinstallingopenvpn": "Error occured while installing openvpn",
        "Erroroccuredwhileinstallingpidof": "Error occured while installing pidof",
        "Erroroccuredwhileinstallingshadowsocks-libev": "Error occured while installing shadowsocks-libev",
        "ErroroccurredwhilegettingSOCKS5credentials": "Error occurred while getting SOCKS5 credentials",
        "Erroroccurredwhileinitiatingtransferamount.": "Error occurred while initiating transfer amount.",
        "Erroroccurredwhilegettingtransactionhistory.": "Error occurred while getting transaction history.",
        "Erroroccuredwhilesubmittingrating": "Error occured while submitting rating",
        "Somethingwentwrong": "Something went wrong",
        "InternalServerError": "Internal Server Error",
        "Oops..!Youhavecrossedthetokenlimit": "Oops..! You have crossed the token limit",
        "Somethingwentwrongwhilegettingtokens": "Something went wrong while getting tokens",
        "Problemfacedinreporting.Tryagainlater": "Problem faced in reporting. Try again later",
        "NotransactionfoundwiththattransactionId": "No transaction found with that transaction Id",
        "Notavalidtransactionhash": "Not a valid transaction hash",
        "ReportedSuccessfully": "Reported Successfully",
        "TransactionFailed": "Transaction Failed",
        "TransactionSuccess": "Transaction Success",
        "Successfullysent150TSENT": "Successfully sent 150 TSENT",
        "Successfullysent100TSENT": "Successfully sent 100 TSENT",
        "InitialPaymentAlert": "Initial Payment Alert",
        "PleaseClickPay": "Please click on pay button to make the initial payment",
        "UsedAllLocked": "You have used all of your locked TSENTs. Please reconnect and pay.",
        "Disconnectingfailed": "Disconnecting failed",


        "Erroroccurredwhileinitiatingthetransaction.": "Error occurred while initiating the transaction.",
        "CurrentlyVPNserverisnotavailable.Pleasetryaftersometime.": "Currently VPN server is not available. Please try after sometime.",
        "StartedVPNsession.": "Started VPN session.",
        "ConnectiontimedoutwhileconnectingtoVPNserver.": "Connection timed out while connecting to VPN server.",
        "InitialVPNpaymentisnotdone.": "Initial VPN payment is not done.",
        "Erroroccurredwhilechekinginitialpaymentstatus.": "Error occurred while cheking initial payment status.",
        "Erroroccurredwhilecheckingdueamount.": "Error occurred while checking due amount.",
        "Yourbalanceislessthan100SENTs.": "Your balance is less than 100 SENTs.",
        "Wrongclientwalletaddressortoken.": "Wrong client wallet address or token.",
        "YouHaveDue": "You have due amount. Please try after clearing the due.",

        "TestTokensalreadyclaimed": "Test Tokens already claimed",
        "Erroroccurredwhiletransferringfreeamount.": "Error occurred while transferring free amount.",
        "SuccessfullytransferredTestTokens": "Successfully transferred Test Tokens",

        "TestSENTunit" : "TestSENT",
        "TestETHunit" : "TestETH",
        "ClaimedBy" : "Tokens Claimed by Service Provider",
        "AddressToSend":"ADDRESS TO SEND",
        "NodeID" : "Node ID",
        "Socks5ComingSoon" : "Socks5 (Coming Soon)",
        "PrivateComingSoon" : "Private (Coming Soon)",
        "VersionInSidebar":"dVPN - alpha-0.1.01",

    },
    ja: {
        'BeCareful': 'ご注意',
        'ToTooltip': 'あなたがセンチネルトークンを送信したいウォレット住所',
        'AmountTool1': '送信したいEthereum / Sentinelトークンの合計。',
        'AmountTool2': 'はい、この財布にはエテリアムも収納できます',
        'GasFieldTool': 'デフォルトのガス制限は21000です',
        'GasPriceTool': 'ガスの単位あたりのあなたが支払う金額',
        'PasswordTool': 'あなたのSentinel AUIDパスワード',
        'Price': '価格 (SENTS/GB)',
        'Cost': '価格',
        'CopyKeys': '安全な場所にあなたの秘密鍵を書き写してください。私達はデータベースにあなたの秘密鍵を格納しないことを忘れないでください。 私達はデータベースを保持しません。 ',
        'YourAddress': 'あなたのアドレス',
        'PrivateKey': '秘密鍵',
        'KeyLocation': 'キーストアファイルの格納場所',
        'YesUnderstand': 'はい、私は理解しました。安全な場所に秘密鍵を保管しました。',
        'GoToDash': 'ダッシュボードへ行く',
        'AmountEmpty': '金額欄が空です',
        'PasswordEmpty': 'パスワードフィールドが空です',
        'AnonymousVPN': 'ブロックチェーンのセキュリティに基づく匿名VPN',
        'OpenSource': 'オープンソースウォレットと安全なサービスプラットフォーム',
        'CreateRestore': 'ウォレット作成／復元',
        'SentinelAnonymity': 'センチネルプラットフォーム',
        'PeerToPeer': 'フリーサービスと匿名ERCトークン取引のマルチチェーン付属のピアツーピアERCベースのプライバシーアプリケーション',
        'BetaVersion': '0.1.0のベータ版',
        'InitialPayment': '最初の支払リマインダ',
        'InorderVPN': 'VPNを使用するために最初に100SENTを支払う必要があります。支払いしてVPNに接続してください。',
        'CreateAUID': 'あなたの匿名ユーザーIDを作成する',
        'CreateTooltip': 'パスワードを入力し、独自のSentinel匿名ユーザーID（AUID）を作成します。',
        'PasswordAUID': 'AUIDを作成するためのパスワードを入力してください',
        'ConfirmPwd': 'パスワードを認証する',
        'SelectKeystore': 'キーストアファイルを選択する',
        'RestoreKeystore': 'キーストア ファイルを復元します。',
        'DidNotMatch': 'パスワードとパスワードの確認が一致しませんでした',
        'KeyPassMatch': 'キーストアとパスワードが一致しません',
        'Create': '作成する',
        'History': '歴史',
        'EthTransactions': 'Eth トランザクション',
        'NoTransactions': 'トランザクションがまだありません。',
        'SentTransactions': 'Sent トランザクション',
        'Send': '送信',
        'To': '宛先',
        'SendTo': '住所に送る',
        'AmountTo': '送信する金額',
        'TokenBal': 'トークンバランス',
        'Convert': 'コンバート',
        'ConvertERC': 'ERC20をSENTに変換する',
        'ExchangeERC': 'センチネルトークンの交換ERC20トークン',
        'From': 'から',
        'Amount': '量',
        'GasLimit': 'Gas リミット',
        'Password': 'パスワード',
        'GasPrice': 'Gas 価格',
        'Next': '次に',
        'Back': '戻る',
        'Out': 'アウト',
        'In': 'に',
        'Status': 'ステータス',
        'Success': '成功',
        'Fail': '失敗します',
        'Copy': 'コピー',
        'City': 'シティ',
        'Country': '国',
        'Due': '支払額',
        'Copied': 'クリップボードに正常にコピーされました',
        'Receive': '受信',
        'GetTokens': '無料トークンを入手',
        'VpnList': 'VPN リスト',
        'NoVPN': 'VPN接続なありません',
        'VpnHistory': 'VPN 歴史',
        "TransactionsHistory": "交易历史",
        'TotalDue': '合計支払額',
        'TotalDuration': '合計期間',
        'TotalData': '合計受信データ',
        'SessionId': 'セッション ID',
        'Sessions': 'セッション',
        'VpnAddress': 'VPN アドレス',
        'Duration': '期間',
        'ReceivedData': '受信データ',
        'Bandwidth': '帯域幅',
        'Latency': '待ち時間',
        'Loading': '読み込んでいます...',
        'DownloadUsage': 'ダウンロードの使用',
        'UploadUsage': 'アップロードの使用',
        'SearchCity': '都市または国を検索',
        'Flag': 'フラグ',
        'Speed': '速度',
        'KeystoreLogin': 'キーストアを入力ログインするパスワード',
        'KeyPass': 'キーストアを入力パスワード',
        'ClickPay': 'クリックして支払う',
        'Location': 'ロケーション',
        'Uhave': 'あなたが持っている',
        'NoServers': '現在、利用可能なVPNサーバーはありません',
        'Time': '時間',
        'PayNow': '現在有料',
        'SelectNode': '接続する任意のノードを選択します。',
        'CheckInternet': 'インターネット接続を確認してください',
        'Disconnect': 'ディスコネクト',
        'DisconnectVPN': '切断されたVPN',
        'Disconnecting': '切断中...',
        'Connecting': '接続中...しばらくお待ちください',
        'AlreadyReport': '既に支払われたか。レポート',
        'ConnectedVPN': '接続されたVPN',
        'List': 'リスト',
        'VPNDetails': 'VPNの詳細',
        'Map': '地図',
        'Pay': '支払う',
        'ClickVPN': '任意のノードをクリックしてVPNに接続します。',
        'Close': '閉じる',
        'Cancel': 'キャンセル',
        'Submit': '提出する',
        'CheckCre': '認証情報を確認しています',
        'Connect': 'コネクト',
        'TestMode': 'テストモードが活性化',


        'WalletTM': 'TENDERMINT',
        'WalletERC': 'ERC20',
        'TSent': 'TSENT',
        'TestNet': 'TESTNET',
        'WalletAddress': 'WALLET ADDRESS',
        'ERC20WalletCopy': 'Copy ERC20 Sent Wallet Address',
        'TMWalletCopy': 'Copy Tendermint Wallet Address',
        'TestSent': 'TEST SENT',
        'Sent': 'SENT',
        'Eth': 'ETH',
        'TestEth': 'TEST ETH',
        'TestNetTM': 'TENDERMINT TESTNET',
        'TestNetETH': 'ETHEREUM TESTNET',
        'RefreshBalTM': 'Refresh TENDERMINT Balance ',
        'RefreshBalETH': 'Refresh ERC20 Balance ',
        'Sending': '送信...',
        'TM': 'TENDERMINT',
        'ETH': 'ETHEREUM',
        'TxHistory': 'TX HISTORY',
        'Account': 'ACCOUNT',
        'Transfer': 'TRANSFER',
        'NoSentTx': 'No SENT Transactions Yet',
        'NoEthTx': 'No ETH Transactions Yet',
        'NodVPNNodes': 'No dVPN nodes found',
        'NoPrevSessions': 'No Previous Sessions',
        'ConnectTodVPN': 'Connect to dVPN',
        'ConnectingdVPN': "Connecting...",
        'Connected': 'Connected',
        'Activated': 'Activated',
        'TMTestNet': 'Tendermint Test Net',
        'ETHTestNet': 'Ethereum Test Net',
        'ETHMainNet': 'Ethereum Main Net',
        'Offline': 'You Are Offline',
        "OpenVPN": "OpenVPN",
        'Socks5': "SOCKS5",
        'Failed': 'Failed',
        'Sents': ' SENTS',
        'Secs': ' sec',
        'MS': " ms",
        'Mbps': ' Mbps',
        'SentPerGb': ' SENT/GB',
        'TSentLocked': 'TSENT Locked',
        'TSentConsumed': 'TSENT Consumed',
        'Note': 'Note: Your account balance is 0 TSENT. You can get some TSENTs for free, click on GET TOKENs above.',
        'TxFailed': 'Transaction Failed',
        'IncorrectPwd': 'Incorrect Password',
        'TxSuccess': 'Transaction done successfully',
        'VpnConnected': 'VPN Connected',
        'WentWrong': 'Something went wrong',
        'EnterTxHash': "Enter txhash of transaction",
        'ErrOccured': 'Error Occured',


        'Algorithm': 'Algorithm',
        'Version': 'Version',
        'Rating': 'Rating',
        'Public': 'Public',
        'Private': 'Private',
        'Selected': 'Selected',
        'OpenVPNList': 'OpenVPN List',
        'GWEI': ' GWEI',
        'Eths': ' ETHS',
        "Refresh": "Refresh",
        "Sentinel": "SENTINEL",

        "SearchdVPNnode": "Search for a dVPN node",
        "SwitchPrivate": "Switch To Private Network",
        "EnterAuthCode": "Please enter your Auth Code to connect to the Private Network",
        "AuthCode": "Auth Code",
        "ToggleMenu": "Toggle Menu",
        "WindowTitle": "Sentinel Network - dVPN - alpha-0.1.0",
        "RunInBackground": "Run in Background",
        "Confirm": "Confirm",
        "CurrentlyConnectedToVPN": "You are currently connected to a VPN",
        "DisconnectOpenVPN": "DisconnectOpenVPN",
        "Edit": "Edit",
        "Undo": "Undo",
        "Redo": "Redo",
        "Cut": "Cut",
        "Paste": "Paste",
        "SelectAll": "Select All",
        "Quit": "Quit",
        "ToggleDevTools": "Toggle Developer Tools",
        "IPAddress": "IP Address",
        "Upload": "Upload",
        "Download": "Download",
        "RateSession": "Rate this session",
        "Comment": "Comment",
        "RatedSuccess": "Rated Successfully",
        "ConnectedToVPN": "Connected to VPN",


        "MessageSuccess": "This is a success message!",
        "MessageErr": "This is an error message!",
        "MessageWarn": "This is a warning message!",
        "MessageInfo": "This is an information message!",
        "CheckStatus": "Check Status",
        "OR": "(OR)",
        "CreateWalletSST": "Create a Wallet on Sentinel Tendermint TestNet (STT) #1",
        "AccountName": "Account Name",
        "AccountPwd": "Account Password",
        "CreateAccount": "Create Account",
        "MB": "MB",
        "OfflineInFooter": "Offline",
        "TxID": "TxID",
        "SentGroup": "SentinelGroup.io",
        "SwapOnPIVX": "Swap on PIVX Tokens",
        "EnterRefundAddr": "Enter refund address",
        "EnterPIVXAddr": "Enter pivx address",
        "Example": "Example",
        "KeyStorePwd": "KEYSTORE PASSWORD",
        "PIVXTokensto": "PIVX Tokens to ",
        "Swap": "SWAP",
        "Swaping": "SWAPING",
        "Total": "Total",
        "TokensToBeSwapped": "tokens to be swapped",
        "Enter": "Enter",
        "RefundAddr": "refund Address",
        "PIVXAddr": "PIVX Address",
        "Expected": "Expected",
        "Tokens": " Tokens",
        "Sentinel[SENT]": "Sentinel [SENT]",
        "NoTokens": "No Tokens Found",
        "Address": "Address",
        "PubKey": "Public Key",
        "Seed": "Seed",
        "GoToSTWallet": "Go To Sentinel Tendermint Wallet",
        "NoVPNUsed": "No VPN Used",
        "ProblemEnablingPrivateNet": "Problem in enabling private net",
        "PrivateNetEnabledWith": "Private Net is Enabled with ",
        "SentTokens": "SENT TOKENS",
        "Balance": "Balance",
        "Converting": "CONVERTING",
        "OpenVpnNotInstalled": "OpenVPN Not Installed.",
        "PleaseGo": "Please go to",
        "OpenVpnPath": "C:\\Users\\(your-user-name)\\AppData\\Local\\Sentinel\\app-0.1.0\\resources\\extras",
        "OpenVpnInstallCmd": "and run openvpn-install-2.3.18-I602-x86_64.exe.",
        "OpenVpnMessage": "Just Install Openvpn without changing installation directory.",
        "YourUserName": "your-user-name",
        "AndRun": "and run",
        "OpenVpnInstallAlert": "OpenVPN Not Installed. Please go to C:\\Users\\(your-user-name)\\AppData\\Local\\Sentinel\\app-0.1.0\\resources\\extras and run openvpn-install-2.3.18-I602-x86_64.exe. Just Install Openvpn without changing installation directory.",
        "ConnectedSocks": "Connected to Socks",


        "Can'tdetectcurrentosplatform.": "Can't detect current os platform.",
        "ConnectingVPNFailed.PleaseTryAgain": "Connecting VPN Failed. Please Try Again",
        "Unabletoreachsentinelserveratthismoment": "Unable to reach sentinel server at this moment",
        "Currentlyserverhassomenetworkissues.Pleasetryotherserver.": "Currently server has some network issues.Please try other server.",
        "Somethingwentwrong.PleaseTryAgain": "Something went wrong.Please Try Again",
        "Erroroccuredwhileinstallingbrew": "Error occured while installing brew",
        "PackageBrewisnotInstalled": "Package Brew is not Installed",
        "Erroroccuredwhileinstallingopenvpn": "Error occured while installing openvpn",
        "Erroroccuredwhileinstallingpidof": "Error occured while installing pidof",
        "Erroroccuredwhileinstallingshadowsocks-libev": "Error occured while installing shadowsocks-libev",
        "ErroroccurredwhilegettingSOCKS5credentials": "Error occurred while getting SOCKS5 credentials",
        "Erroroccurredwhileinitiatingtransferamount.": "Error occurred while initiating transfer amount.",
        "Erroroccurredwhilegettingtransactionhistory.": "Error occurred while getting transaction history.",
        "Erroroccuredwhilesubmittingrating": "Error occured while submitting rating",
        "Somethingwentwrong": "Something went wrong",
        "InternalServerError": "Internal Server Error",
        "Oops..!Youhavecrossedthetokenlimit": "Oops..! You have crossed the token limit",
        "Somethingwentwrongwhilegettingtokens": "Something went wrong while getting tokens",
        "Problemfacedinreporting.Tryagainlater": "Problem faced in reporting. Try again later",
        "NotransactionfoundwiththattransactionId": "No transaction found with that transaction Id",
        "Notavalidtransactionhash": "Not a valid transaction hash",
        "ReportedSuccessfully": "Reported Successfully",
        "TransactionFailed": "Transaction Failed",
        "TransactionSuccess": "Transaction Success",
        "Successfullysent150TSENT": "Successfully sent 150 TSENT",
        "Successfullysent100TSENT": "Successfully sent 100 TSENT",
        "InitialPaymentAlert": "Initial Payment Alert",
        "PleaseClickPay": "Please click on pay button to make the initial payment",
        "UsedAllLocked": "You have used all of your locked TSENTs. Please reconnect and pay.",
        "Disconnectingfailed": "Disconnecting failed",


        "Erroroccurredwhileinitiatingthetransaction.": "Error occurred while initiating the transaction.",
        "CurrentlyVPNserverisnotavailable.Pleasetryaftersometime.": "Currently VPN server is not available. Please try after sometime.",
        "StartedVPNsession.": "Started VPN session.",
        "ConnectiontimedoutwhileconnectingtoVPNserver.": "Connection timed out while connecting to VPN server.",
        "InitialVPNpaymentisnotdone.": "Initial VPN payment is not done.",
        "Erroroccurredwhilechekinginitialpaymentstatus.": "Error occurred while cheking initial payment status.",
        "Erroroccurredwhilecheckingdueamount.": "Error occurred while checking due amount.",
        "Yourbalanceislessthan100SENTs.": "Your balance is less than 100 SENTs.",
        "Wrongclientwalletaddressortoken.": "Wrong client wallet address or token.",
        "YouHaveDue": "You have due amount. Please try after clearing the due.",


        "TestTokensalreadyclaimed": "Test Tokens already claimed",
        "Erroroccurredwhiletransferringfreeamount.": "Error occurred while transferring free amount.",
        "SuccessfullytransferredTestTokens": "Successfully transferred Test Tokens",

        "TestSENTunit" : "TestSENT",
        "TestETHunit" : "TestETH",
        "ClaimedBy" : "Tokens Claimed by Service Provider",
        "AddressToSend":"ADDRESS TO SEND",
        "NodeID" : "Node ID",
        "Socks5ComingSoon" : "Socks5 (Coming Soon)",
        "PrivateComingSoon" : "Private (Coming Soon)",
        "VersionInSidebar":"dVPN - alpha-0.1.01",
    },
    es: {
        'History': 'HISTORIAL',
        'EthTransactions': 'Transacciones de ETH',
        'SentTransactions': 'Transacciones de SENT',
        'NoTransactions': 'No hay transacciones',
        'Send': 'ENVIAR',
        'To': 'Destino',
        'SendTo': 'ENVIAR A LA DIRECCIÓN',
        'AmountTo': 'CANTIDAD PARA ENVIAR',
        'TokenBal': 'Balance de tokens',
        'Convert': 'CONVERTIR',
        'ConvertERC': 'Convierte ERC20 a SENT',
        'ExchangeERC': 'Intercambio de tokens ERC20 para tokens Sentinel',
        'From': 'Origen',
        'Amount': 'Cantidad',
        'GasLimit': 'Límite Gas',
        'Password': 'Contraseña',
        'GasPrice': 'Precio Gas',
        'Next': 'SIGUIENTE',
        'Back': 'ATRÁS',
        'Out': 'FUERA',
        'In': 'DENTRO',
        'Status': 'Estado',
        'Success': 'Conseguido',
        'Fail': 'Fallo',
        'Copy': 'Copiar',
        'City': 'Ciudad',
        'Country': 'País',
        'Due': 'Esperado',
        'Copied': 'Copiado al portapapeles con éxito',
        'Receive': 'RECIBIR',
        'GetTokens': 'OBTÉN TOKENS GRATIS',
        'VpnList': 'LISTA VPN',
        'SelectNode': 'Selecciona cualquier nodo para conectarse',
        'CheckInternet': 'Comprueba tu conexión a internet',
        'NoVPN': 'Ningún VPN conectado',
        'VpnHistory': 'HISTORIAL VPN',
        "TransactionsHistory": "HISTORIA DE TRANSACCIONES",
        'TotalDue': 'Total esperado',
        'TotalDuration': 'Duración total',
        'TotalData': 'Total de datos recibidos',
        'SessionId': 'ID de sesión',
        'Sessions': 'Sesiones',
        'VpnAddress': 'Dirección VPN',
        'Bandwidth': 'Ancho de banda',
        'Latency': 'Latencia',
        'Loading': 'Cargando...',
        'Speed': 'Velocidad',
        'Location': 'Localización',
        'Duration': 'Duración',
        'DownloadUsage': 'Uso de bajada',
        'UploadUsage': 'Uso de subida',
        'Disconnect': 'Desconectar',
        'DisconnectVPN': 'VPN desconectado',
        'ConnectedVPN': 'VPN conectado',
        'Disconnecting': 'Desconectando...',
        'Connecting': 'Conectando...Espera',
        'ClickPay': 'Clica para pagar',
        'ReceivedData': 'Datos recibidos',
        'SearchCity': 'Buscar ciudad o país',
        'Time': 'Tiempo',
        'NoServers': 'Actualmente no hay servidores VPN disponibles',
        'PayNow': 'Pagar ahora',
        'AlreadyReport': 'Ya ha sido pagado? Repórtalo',
        'List': 'LISTA',
        'VPNDetails': 'Detalles VPN',
        'ClickVPN': 'Clica en cualquier nodo para conectarte al VPN',
        'KeystoreLogin': 'Introduce tu contraseña Keystore para acceder',
        'KeyPass': 'Introduce tu contraseña Keystore',
        'CheckCre': 'Comprobando credenciales...',
        'Map': 'MAPA',
        'Pay': 'Pagar',
        'Flag': 'Bandera',
        'Uhave': 'Tú tienes',
        'Close': 'Cerrar',
        'Cancel': 'CANCELAR',
        'Connect': 'CONECTAR',
        'Submit': 'Aceptar',
        'TestMode': 'MODO TEST ACTIVADO',
        'AnonymousVPN': 'VPN Anónima respaldada por la seguridad de blockchain',
        'OpenSource': 'Wallet de código abierto y plataforma de servicios segura',
        'CreateRestore': 'Crear / Restaurar Wallet',
        'SentinelAnonymity': 'Sentinel: plataforma dedicada al anonimato',
        'PeerToPeer': 'Aplicación P2P con privacidad, basada en ERC, y con una multichain para servicios exentos de gas y transacciones anónimas de tokens ERC',
        'BetaVersion': 'Versión Beta 0.1.0 con Testnet',
        'InitialPayment': 'Recordatorio de pago inicial',
        'InorderVPN': 'Con el fin de usar la VPN, usted debe pagar 100 SENTs. Por favor, paga y prueba de conectarte a la VPN.',
        'CreateAUID': 'Crea tu ID de Usuario Anónimo',
        'CreateTooltip': 'Introduce una contraseña y crea tu propio ID de Usuario Anónimo (AUID) de Sentinel',
        'PasswordAUID': 'Introduce una contraseña para crear el AUID',
        'ConfirmPwd': 'Confirmar contraseña',
        'Create': 'Crear',
        'SelectKeystore': 'Selecciona el archivo Keystore',
        'RestoreKeystore': 'Restaurar el archivo Keystore',
        'DidNotMatch': 'La contraseña y la confirmación de la misma no coinciden',
        'KeyPassMatch': 'La contraseña y el Keystore no coinciden',
        'BeCareful': 'Ten cuidado',
        'CopyKeys': "Copia tus llaves en un lugar seguro. Recuerda que no almacenamos ninguna llave en nuestra base de datos.",
        'YourAddress': 'Tu dirección',
        'PrivateKey': 'Llave privada',
        'KeyLocation': 'Tu archivo Keystore está almacenado en',
        'YesUnderstand': 'Sí, lo he entendido, y he copiado mis llaves en un lugar seguro',
        'GoToDash': 'Ir al panel de admin.',
        'AmountEmpty': 'El campo de la cantidad está vacío',
        'PasswordEmpty': 'El campo de la contraseña está vacío',
        'ToTooltip': 'La dirección de Wallet a la que quieres enviar tokens de Sentinel',
        'AmountTool1': 'Total de ETH/SENT que quieres enviar.',
        'AmountTool2': 'Sí, este wallet también puede guardar ETH.',
        'GasFieldTool': '21000 es el límite de gas estándar',
        'GasPriceTool': 'Cantidad que pagas por cada unidad de gas',
        'PasswordTool': 'Tu contraseña AUID de Sentinel',
        'Price': 'Precio (SENTS/GB)',
        'Cost': 'Precio',

        'WalletTM': 'TENDERMINT',
        'WalletERC': 'ERC20',
        'TSent': 'TSENT',
        'TestNet': 'TESTNET',
        'WalletAddress': 'WALLET ADDRESS',
        'ERC20WalletCopy': 'Copy ERC20 Sent Wallet Address',
        'TMWalletCopy': 'Copy Tendermint Wallet Address',
        'TestSent': 'TEST SENT',
        'Sent': 'SENT',
        'Eth': 'ETH',
        'TestEth': 'TEST ETH',
        'TestNetTM': 'TENDERMINT TESTNET',
        'TestNetETH': 'ETHEREUM TESTNET',
        'RefreshBalTM': 'Refresh TENDERMINT Balance ',
        'RefreshBalETH': 'Refresh ERC20 Balance ',
        'Sending': 'enviando...',
        'TM': 'TENDERMINT',
        'ETH': 'ETHEREUM',
        'TxHistory': 'TX HISTORY',
        'Account': 'ACCOUNT',
        'Transfer': 'TRANSFER',
        'NoSentTx': 'No SENT Transactions Yet',
        'NoEthTx': 'No ETH Transactions Yet',
        'NodVPNNodes': 'No dVPN nodes found',
        'NoPrevSessions': 'No Previous Sessions',
        'ConnectTodVPN': 'Connect to dVPN',
        'ConnectingdVPN': "Connecting...",
        'Connected': 'Connected',
        'Activated': 'Activated',
        'TMTestNet': 'Tendermint Test Net',
        'ETHTestNet': 'Ethereum Test Net',
        'ETHMainNet': 'Ethereum Main Net',
        'Offline': 'You Are Offline',
        "OpenVPN": "OpenVPN",
        'Socks5': "SOCKS5",
        'Failed': 'Failed',
        'Sents': ' SENTS',
        'Secs': ' sec',
        'MS': " ms",
        'Mbps': ' Mbps',
        'SentPerGb': ' SENT/GB',
        'TSentLocked': 'TSENT Locked',
        'TSentConsumed': 'TSENT Consumed',
        'Note': 'Note: Your account balance is 0 TSENT. You can get some TSENTs for free, click on GET TOKENs above.',
        'TxFailed': 'Transaction Failed',
        'IncorrectPwd': 'Incorrect Password',
        'TxSuccess': 'Transaction done successfully',
        'VpnConnected': 'VPN Connected',
        'WentWrong': 'Something went wrong',
        'EnterTxHash': "Enter txhash of transaction",
        'ErrOccured': 'Error Occured',


        'Algorithm': 'Algorithm',
        'Version': 'Version',
        'Rating': 'Rating',
        'Public': 'Public',
        'Private': 'Private',
        'Selected': 'Selected',
        'OpenVPNList': 'OpenVPN List',
        'GWEI': ' GWEI',
        'Eths': ' ETHS',
        "Refresh": "Refresh",
        "Sentinel": "SENTINEL",

        "SearchdVPNnode": "Search for a dVPN node",
        "SwitchPrivate": "Switch To Private Network",
        "EnterAuthCode": "Please enter your Auth Code to connect to the Private Network",
        "AuthCode": "Auth Code",
        "ToggleMenu": "Toggle Menu",
        "WindowTitle": "Sentinel Network - dVPN - alpha-0.1.0",
        "RunInBackground": "Run in Background",
        "Confirm": "Confirm",
        "CurrentlyConnectedToVPN": "You are currently connected to a VPN",
        "DisconnectOpenVPN": "DisconnectOpenVPN",
        "Edit": "Edit",
        "Undo": "Undo",
        "Redo": "Redo",
        "Cut": "Cut",
        "Paste": "Paste",
        "SelectAll": "Select All",
        "Quit": "Quit",
        "ToggleDevTools": "Toggle Developer Tools",
        "IPAddress": "IP Address",
        "Upload": "Upload",
        "Download": "Download",
        "RateSession": "Rate this session",
        "Comment": "Comment",
        "RatedSuccess": "Rated Successfully",
        "ConnectedToVPN": "Connected to VPN",


        "MessageSuccess": "This is a success message!",
        "MessageErr": "This is an error message!",
        "MessageWarn": "This is a warning message!",
        "MessageInfo": "This is an information message!",
        "CheckStatus": "Check Status",
        "OR": "(OR)",
        "CreateWalletSST": "Create a Wallet on Sentinel Tendermint TestNet (STT) #1",
        "AccountName": "Account Name",
        "AccountPwd": "Account Password",
        "CreateAccount": "Create Account",
        "MB": "MB",
        "OfflineInFooter": "Offline",
        "TxID": "TxID",
        "SentGroup": "SentinelGroup.io",
        "SwapOnPIVX": "Swap on PIVX Tokens",
        "EnterRefundAddr": "Enter refund address",
        "EnterPIVXAddr": "Enter pivx address",
        "Example": "Example",
        "KeyStorePwd": "KEYSTORE PASSWORD",
        "PIVXTokensto": "PIVX Tokens to ",
        "Swap": "SWAP",
        "Swaping": "SWAPING",
        "Total": "Total",
        "TokensToBeSwapped": "tokens to be swapped",
        "Enter": "Enter",
        "RefundAddr": "refund Address",
        "PIVXAddr": "PIVX Address",
        "Expected": "Expected",
        "Tokens": " Tokens",
        "Sentinel[SENT]": "Sentinel [SENT]",
        "NoTokens": "No Tokens Found",
        "Address": "Address",
        "PubKey": "Public Key",
        "Seed": "Seed",
        "GoToSTWallet": "Go To Sentinel Tendermint Wallet",
        "NoVPNUsed": "No VPN Used",
        "ProblemEnablingPrivateNet": "Problem in enabling private net",
        "PrivateNetEnabledWith": "Private Net is Enabled with ",
        "SentTokens": "SENT TOKENS",
        "Balance": "Balance",
        "Converting": "CONVERTING",
        "OpenVpnNotInstalled": "OpenVPN Not Installed.",
        "PleaseGo": "Please go to",
        "OpenVpnPath": "C:\\Users\\(your-user-name)\\AppData\\Local\\Sentinel\\app-0.1.0\\resources\\extras",
        "OpenVpnInstallCmd": "and run openvpn-install-2.3.18-I602-x86_64.exe.",
        "OpenVpnMessage": "Just Install Openvpn without changing installation directory.",
        "YourUserName": "your-user-name",
        "AndRun": "and run",
        "OpenVpnInstallAlert": "OpenVPN Not Installed. Please go to C:\\Users\\(your-user-name)\\AppData\\Local\\Sentinel\\app-0.1.0\\resources\\extras and run openvpn-install-2.3.18-I602-x86_64.exe. Just Install Openvpn without changing installation directory.",
        "ConnectedSocks": "Connected to Socks",

        "Can'tdetectcurrentosplatform.": "Can't detect current os platform.",
        "ConnectingVPNFailed.PleaseTryAgain": "Connecting VPN Failed. Please Try Again",
        "Unabletoreachsentinelserveratthismoment": "Unable to reach sentinel server at this moment",
        "Currentlyserverhassomenetworkissues.Pleasetryotherserver.": "Currently server has some network issues.Please try other server.",
        "Somethingwentwrong.PleaseTryAgain": "Something went wrong.Please Try Again",
        "Erroroccuredwhileinstallingbrew": "Error occured while installing brew",
        "PackageBrewisnotInstalled": "Package Brew is not Installed",
        "Erroroccuredwhileinstallingopenvpn": "Error occured while installing openvpn",
        "Erroroccuredwhileinstallingpidof": "Error occured while installing pidof",
        "Erroroccuredwhileinstallingshadowsocks-libev": "Error occured while installing shadowsocks-libev",
        "ErroroccurredwhilegettingSOCKS5credentials": "Error occurred while getting SOCKS5 credentials",
        "Erroroccurredwhileinitiatingtransferamount.": "Error occurred while initiating transfer amount.",
        "Erroroccurredwhilegettingtransactionhistory.": "Error occurred while getting transaction history.",
        "Erroroccuredwhilesubmittingrating": "Error occured while submitting rating",
        "Somethingwentwrong": "Something went wrong",
        "InternalServerError": "Internal Server Error",
        "Oops..!Youhavecrossedthetokenlimit": "Oops..! You have crossed the token limit",
        "Somethingwentwrongwhilegettingtokens": "Something went wrong while getting tokens",
        "Problemfacedinreporting.Tryagainlater": "Problem faced in reporting. Try again later",
        "NotransactionfoundwiththattransactionId": "No transaction found with that transaction Id",
        "Notavalidtransactionhash": "Not a valid transaction hash",
        "ReportedSuccessfully": "Reported Successfully",
        "TransactionFailed": "Transaction Failed",
        "TransactionSuccess": "Transaction Success",
        "Successfullysent150TSENT": "Successfully sent 150 TSENT",
        "Successfullysent100TSENT": "Successfully sent 100 TSENT",
        "InitialPaymentAlert": "Initial Payment Alert",
        "PleaseClickPay": "Please click on pay button to make the initial payment",
        "UsedAllLocked": "You have used all of your locked TSENTs. Please reconnect and pay.",
        "Disconnectingfailed": "Disconnecting failed",


        "Erroroccurredwhileinitiatingthetransaction.": "Error occurred while initiating the transaction.",
        "CurrentlyVPNserverisnotavailable.Pleasetryaftersometime.": "Currently VPN server is not available. Please try after sometime.",
        "StartedVPNsession.": "Started VPN session.",
        "ConnectiontimedoutwhileconnectingtoVPNserver.": "Connection timed out while connecting to VPN server.",
        "InitialVPNpaymentisnotdone.": "Initial VPN payment is not done.",
        "Erroroccurredwhilechekinginitialpaymentstatus.": "Error occurred while cheking initial payment status.",
        "Erroroccurredwhilecheckingdueamount.": "Error occurred while checking due amount.",
        "Yourbalanceislessthan100SENTs.": "Your balance is less than 100 SENTs.",
        "Wrongclientwalletaddressortoken.": "Wrong client wallet address or token.",
        "YouHaveDue": "You have due amount. Please try after clearing the due.",


        "TestTokensalreadyclaimed": "Test Tokens already claimed",
        "Erroroccurredwhiletransferringfreeamount.": "Error occurred while transferring free amount.",
        "SuccessfullytransferredTestTokens": "Successfully transferred Test Tokens",

        "TestSENTunit" : "TestSENT",
        "TestETHunit" : "TestETH",
        "ClaimedBy" : "Tokens Claimed by Service Provider",
        "AddressToSend":"ADDRESS TO SEND",
        "NodeID" : "Node ID",
        "Socks5ComingSoon" : "Socks5 (Coming Soon)",
        "PrivateComingSoon" : "Private (Coming Soon)",
        "VersionInSidebar":"dVPN - alpha-0.1.01",
    },
    ru: {
        "History": "История",
        "EthTransactions": "Транзакции ETH",
        "SentTransactions": "Транзакции SENT",
        "NoTransactions": "Транзакций пока нет",
        "Send": "Отправить",
        "To": "Получатель",
        'SendTo': 'ОТПРАВИТЬ НА АДРЕС',
        'AmountTo': 'КОЛИЧЕСТВО ДЛЯ ОТПРАВКИ',
        'TokenBal': 'ТАКЖЕ БАЛАНС',
        'Convert': 'КОНВЕРТИРОВАТЬ',
        'ConvertERC': 'Преобразование ERC20 в SENT',
        'ExchangeERC': 'Биржевые маркеры ERC20 для токенов Sentinel',
        "From": "Отправитель",
        "Amount": "Количество",
        "GasLimit": "Лимит Газа",
        "Password": "Пароль",
        "GasPrice": "Цена Газа",
        "Next": "Следующая",
        "Back": "Назад",
        "Out": "Отправка",
        "In": "Получение",
        "Status": "Статус",
        "Success": "Успешно",
        "Fail": "Ошибка",
        "Copy": "Копировать",
        "City": "Город",
        "Country": "Страна",
        "Due": "Долг",
        "Copied": "Успешно скопировано в буфер обмена",
        "Receive": "Получить",
        "GetTokens": "Получить бесплатные токены",
        "VpnList": "Сервера",
        "SelectNode": "Выберите узел для подключения",
        "CheckInternet": "Проверить интернет-соединение",
        "NoVPN": "Нет подключения к VPN",
        "VpnHistory": "Подключения",
        "TransactionsHistory": "История переходов",
        "TotalDue": "Общий долг",
        "TotalDuration": "Общая длительность",
        "TotalData": "Полученно данных за все время",
        "SessionId": "ID Сеанса",
        "Sessions": "Сеансы",
        "VpnAddress": "Адрес VPN",
        "Bandwidth": "Трафик",
        "Latency": "Задержка",
        "Loading": "Загрузка...",
        "Speed": "Скорость",
        "Location": "Местоположение",
        "Duration": "Длительность",
        "DownloadUsage": "Скачано",
        "UploadUsage": "Отдано",
        "Disconnect": "Отключение",
        "DisconnectVPN": "Отключение от VPN",
        "ConnectedVPN": "Поключено к VPN",
        "Disconnecting": "Отключаюсь...",
        "Connecting": "Подключаюсь...Ожидайте",
        "ClickPay": "Нажмите для оплаты",
        "ReceivedData": "Полученно данных",
        "SearchCity": "Поиск города или страны",
        "Time": "Время",
        "NoServers": "Нет доступных VPN в данный момент",
        "PayNow": "Оплатить сейчас",
        "AlreadyReport": "Уже оплатил? Подтверди",
        "List": "Список",
        "VPNDetails": "Характеристики VPN",
        "ClickVPN": "Нажмите на любой узел чтобы подключится к VPN",
        "KeystoreLogin": "Введите пароль от хранилища для входа",
        "KeyPass": "Введите пароль от хранилища",
        "CheckCre": "Проверка полномочий...",
        "Map": "Карта",
        "Pay": "Оплатить",
        "Flag": "Флаг",
        "Uhave": "Вы имеете",
        "Close": "Закрыть",
        "Cancel": "Отменить",
        "Connect": "Подключиться",
        "Submit": "Направить",
        "TestMode": "Тестовая версия активирована",
        "AnonymousVPN": "Анонимная VPN-сеть при поддержке блокчейн-безопасности",
        "OpenSource": "Кошелек с открытым исходным кодом и безопасной сервисной платформой",
        "CreateRestore": "Создать / Восстановить кошелек",
        "SentinelAnonymity": "Анонимная платформа Sentinel",
        "PeerToPeer": "Пиринговый ERC-поддерживающий набор приватных приложений с мультичейном для безгазовых услуг and анонимных транзакций ERC-токенов",
        "BetaVersion": "Бета-версия 0.1.0 с тестовой сетью",
        "InitialPayment": "Напоминание о платеже",
        "InorderVPN": "Чтобы воспользоваться VPN, вам нужно заплатить 100 SENT для начала. Пожалуйста, оплатите и попытайтесь подключиться к VPN.",
        "CreateAUID": "Создайте свой ID анонимного пользователя",
        "CreateTooltip": "Введите пароль и создайте свой собственный ID анонимного пользователя (AUID)",
        "PasswordAUID": "Введите пароль, чтобы создать AUID",
        "ConfirmPwd": "Подтвердить пароль",
        "Create": "Создать",
        "SelectKeystore": "Выбрать файл хранилища",
        "RestoreKeystore": "Восстановить файл хранилища",
        "DidNotMatch": "Пароли не совпадают",
        "KeyPassMatch": "Хранилище и пароль не совпадают",
        "BeCareful": "Будьте осторожны",
        "CopyKeys": "Храните свои ключи в надежном месте. Запомните, мы не храним ваши ключи всвоей базе.",
        "YourAddress": "Ваш адрес",
        "PrivateKey": "Приватный ключ",
        "KeyLocation": "Ваш файл хранилища содержится в",
        "YesUnderstand": "Да, Я понимаю, Я сохранил свои ключи в надежное место",
        "GoToDash": "направиться в панель управления",
        "AmountEmpty": "Поле оплаты пусто",
        "PasswordEmpty": "Поле пароля пусто",
        "ToTooltip": "Адрес кошелька, на который вы хотите отправить токены Sentinel",
        "AmountTool1": "Общее количество Ethereum/Sentinel токенов, которые вы хотите отправить.",
        "AmountTool2": "Да, в этом кошельке можно хранить Ethereum.",
        "GasFieldTool": "21000 - это оптимальный лимит газа",
        "GasPriceTool": "Цена за единицу газа",
        "PasswordTool": "Ваш Sentinel AUID-пароль",
        "Price": "Цена (SENTS/ГБ)",
        "Cost": "Стоимость",

        'WalletTM': 'TENDERMINT',
        'WalletERC': 'ERC20',
        'TSent': 'TSENT',
        'TestNet': 'ТЕСТОВАЯ СЕТЬ',
        'WalletAddress': 'АДРЕС КОШЕЛЬКА',
        'ERC20WalletCopy': 'Скопировать адрес ERC20-кошелька',
        'TMWalletCopy': 'Копировать адрес кошелька Tendermint',
        'TestSent': 'TEST SENT',
        'Sent': 'SENT',
        'Eth': 'ETH',
        'TestEth': 'TEST ETH',
        'TestNetTM': 'ТЕСТОВАЯ СЕТЬ TENDERMINT',
        'TestNetETH': 'ТЕСТОВАЯ СЕТЬ ETHEREUM',
        'RefreshBalTM': 'Обновить баланс TENDERMINT ',
        'RefreshBalETH': 'Обновить баланс ERC20 ',
        'Sending': 'отправка...',
        'TM': 'TENDERMINT',
        'ETH': 'ETHEREUM',
        'TxHistory': 'Транзакции',
        'Account': 'Аккаунт',
        'Transfer': 'Перевести',
        'NoSentTx': 'Пока транзакций с SENT нет',
        'NoEthTx': 'Пока транзакций с ETH нет',
        'NodVPNNodes': 'dVPN-Серверов не найдено',
        'NoPrevSessions': 'Нет предыдущих сессий',
        'ConnectTodVPN': 'Подключиться к dVPN',
        'ConnectingdVPN': "Подключение...",
        'Connected': 'Подключено',
        'Activated': 'Активировано',
        'TMTestNet': 'Тестовая сеть Tendermint',
        'ETHTestNet': 'Тестовая Сеть Ethereum',
        'ETHMainNet': 'Основная Cеть Ethereum',
        'Offline': 'Возникла ошибка при инициировании суммы перевода.',
        "OpenVPN": "OpenVPN",
        'Socks5': "SOCKS5",
        'Failed': 'не удалось',
        'Sents': ' SENTS',
        'Secs': ' sec',
        'MS': " ms",
        'Mbps': ' МБит/c',
        'SentPerGb': ' SENT/ГБ',
        'TSentLocked': 'Заложено TSENT',
        'TSentConsumed': 'Использовано TSENT',
        'Note': 'Заметка: На вашем балансе 0 TSENT. Вы можете получить некоторые TSENTs бысплатно. Для этого нажмите GET TOKENs.',
        'TxFailed': 'Транзакция не прошла',
        'IncorrectPwd': 'Неверный пароль',
        'TxSuccess': 'Транзакция прошла успешно',
        'VpnConnected': 'VPN-Подключение',
        'WentWrong': 'Что-то пошло не так',
        'EnterTxHash': "Введите хэш транзакции",
        'ErrOccured': 'Возникла ошибка',


        'Algorithm': 'Алгоритм',
        'Version': 'Версия',
        'Rating': 'Рейтинг',
        'Public': 'Public',
        'Private': 'Private',
        'Selected': 'Выбрано',
        'OpenVPNList': 'Список OpenVPN',
        'GWEI': ' GWEI',
        'Eths': ' ETHS',
        "Refresh": "Обновить",
        "Sentinel": "SENTINEL",

        "SearchdVPNnode": "Поиск dVPN-Сервераe",
        "SwitchPrivate": "Переключиться на Приватную Сеть",
        "EnterAuthCode": "Пожалуйста",
        "AuthCode": "Код Аутентификации",
        "ToggleMenu": "Открыть меню",
        "WindowTitle": "Sentinel Network - dVPN - alpha-0.1.0",
        "RunInBackground": "Запустить в фоновом режиме",
        "Confirm": "Подтвердить",
        "CurrentlyConnectedToVPN": "Вы уже подключены к VPN",
        "DisconnectOpenVPN": "Отключение от OpenVPN",
        "Edit": "Редактировать",
        "Undo": "Undo",
        "Redo": "Redo",
        "Cut": "Cut",
        "Paste": "Вставить",
        "SelectAll": "Select All",
        "Quit": "Quit",
        "ToggleDevTools": "Toggle Developer Tools",
        "IPAddress": "IP-Адрес",
        "Upload": "загружать",
        "Download": "Скачать",
        "RateSession": "Оценить этот сеанс",
        "Comment": "Заметка",
        "RatedSuccess": "Успешно оценено",
        "ConnectedToVPN": "Подключено к VPN",


        "MessageSuccess": "Сообщение о успехе!",
        "MessageErr": "Сообщение об ошибке!",
        "MessageWarn": "Сообщение о предупреждении!",
        "MessageInfo": "Сообщение о информации!",
        "CheckStatus": "Проверить статус",
        "OR": "(OR)",
        "CreateWalletSST": "Создать кошелек в Тестовой сети Sentinel Tendermint (STT) #1",
        "AccountName": "Логин",
        "AccountPwd": "Пароль",
        "CreateAccount": "Создать Аккаунт",
        "MB": "МБ",
        "OfflineInFooter": "Не в сети",
        "TxID": "ID Транзакции",
        "SentGroup": "SentinelGroup.io",
        "SwapOnPIVX": "Обмен токенов PIVX",
        "EnterRefundAddr": "Введите адрес возврата",
        "EnterPIVXAddr": "Введите PIVX-Адрес",
        "Example": "Пример",
        "KeyStorePwd": "ПАРОЛЬ ОТ ХРАНИЛИЩА",
        "PIVXTokensto": "PIVX токены в ",
        "Swap": "ОБМЕН",
        "Swaping": "ОБМЕНИВАНИЕ",
        "Total": "Всего",
        "TokensToBeSwapped": "Токенов для обмена",
        "Enter": "Ввести",
        "RefundAddr": "Адрес возврата",
        "PIVXAddr": "Адрес PIVX",
        "Expected": "Ожидаемый",
        "Tokens": " Токены",
        "Sentinel[SENT]": "Sentinel [SENT]",
        "NoTokens": "Токенов не обнаружено",
        "Address": "Адрес",
        "PubKey": "Публичный ключ",
        "Seed": "Seed",
        "GoToSTWallet": "Перейти к кошельку Sentinel Tendermint",
        "NoVPNUsed": "Нет использования VPN",
        "ProblemEnablingPrivateNet": "Проблема обеспечения частной сети",
        "PrivateNetEnabledWith": "Приватная Сеть включена с ",
        "SentTokens": "Токены SENT",
        "Balance": "Баланс",
        "Converting": "КОНВЕРТАЦИЯ",
        "OpenVpnNotInstalled": "OpenVPN не установлен.",
        "PleaseGo": "Оповещение о платеже",
        "OpenVpnPath": "C:\\Users\\(your-user-name)\\AppData\\Local\\Sentinel\\app-0.1.0\\resources\\extras",
        "OpenVpnInstallCmd": "and run openvpn-install-2.3.18-I602-x86_64.exe.",
        "OpenVpnMessage": "Just Install Openvpn without changing installation directory.",
        "YourUserName": "your-user-name",
        "AndRun": "and run",
        "OpenVpnInstallAlert": "OpenVPN не установлен. Пройдите к C:\\Users\\(your-user-name)\\AppData\\Local\\Sentinel\\app-0.1.0\\resources\\extras. и запустите openvpn-install-2.3.18-I602-x86_64.exe. Просто установите OpenVPN без изменения директорий.",
        "ConnectedSocks": "Подключено к Socks5",


        "Can'tdetectcurrentosplatform.": "Невозможно определить операционную систему.",
        "ConnectingVPNFailed.PleaseTryAgain": "Подключение к VPN отменено. Попробуйте еще раз.",
        "Unabletoreachsentinelserveratthismoment": "Невозможно подключиться к серверам Sentinel в данный момент",
        "Currentlyserverhassomenetworkissues.Pleasetryotherserver.": "На данном VPN-Сервере происходят технические неполадки. Попробуйте подсоединиться позже.",
        "Somethingwentwrong.PleaseTryAgain": "Что-то пошло не так. Попробуйте еще раз.",
        "Erroroccuredwhileinstallingbrew": "Возникла ошибка при установке Brew",
        "PackageBrewisnotInstalled": "Package Brew не установлен.",
        "Erroroccuredwhileinstallingopenvpn": "Возникла ошибка при установке openvpn",
        "Erroroccuredwhileinstallingpidof": "Возникла ошибка при установке pidof",
        "Erroroccuredwhileinstallingshadowsocks-libev": "Error occured while installing shadowsocks-libev",
        "ErroroccurredwhilegettingSOCKS5credentials": "Возникла ошибка при получении SOCKS5 данных",
        "Erroroccurredwhileinitiatingtransferamount.": "Возникла ошибка при инициировании суммы перевода.",
        "Erroroccurredwhilegettingtransactionhistory.": "Возникла ошибка при отображении истории транзакций.",
        "Erroroccuredwhilesubmittingrating": "Возникла ошибка при отправке оценки сервиса",
        "Somethingwentwrong": "Что-то пошло не так",
        "InternalServerError": "Внутренняя ошибка",
        "Oops..!Youhavecrossedthetokenlimit": "Упс..! Вы превысили лимит токенов.",
        "Somethingwentwrongwhilegettingtokens": "При получении токенов произошла ошибка",
        "Problemfacedinreporting.Tryagainlater": "Problem faced in reporting. Try again later",
        "NotransactionfoundwiththattransactionId": "Не найдено транзакций с таким ID",
        "Notavalidtransactionhash": "Некорректный хэш транзакции",
        "ReportedSuccessfully": "Подтверждено успешно",
        "TransactionFailed": "Транзакция не прошла",
        "TransactionSuccess": "Транзакция прошла успешно",
        "Successfullysent150TSENT": "Успешно отправлено 150 TSENT",
        "Successfullysent100TSENT": "Успешно отправлено 100 TSENT",
        "InitialPaymentAlert": "Первоначальный платеж",
        "PleaseClickPay": "Пожалуйста, нажмите кнопку оплаты для погашения задолжности.",
        "UsedAllLocked": "Вы использовали все ваши TSENTы. Переподключитесь и оплатите.",
        "Disconnectingfailed": "Отключение недоступно",


        "Erroroccurredwhileinitiatingthetransaction.": "Возникла ошибка при отправке транзакции",
        "CurrentlyVPNserverisnotavailable.Pleasetryaftersometime.": "Данный VPN-Сервер не доступен. Попробуйте подключиться к другим или подождать какое-то время.",
        "StartedVPNsession.": "Начало VPN-Сессии",
        "ConnectiontimedoutwhileconnectingtoVPNserver.": "Время ожидания превысило допустимый уровень при подключении к VPN.",
        "InitialVPNpaymentisnotdone.": "Первоначальный платеж не проплачен.",
        "Erroroccurredwhilechekinginitialpaymentstatus.": "Возникла ошибка при отправке платежа",
        "Erroroccurredwhilecheckingdueamount.": "Error occurred while checking due amount.",
        "Yourbalanceislessthan100SENTs.": "На вашем балансе меньше 100 SENTs",
        "Wrongclientwalletaddressortoken.": "Wrong client wallet address or token.",
        "YouHaveDue": "У вас есть задолженность. Оплатите предыдущую сессиюи попробуйте подключиться позже.",

        "TestTokensalreadyclaimed": "Тестовые токены уже отправлены",
        "Erroroccurredwhiletransferringfreeamount.": "Возникла ошибка при отправке бесплатных токенов",
        "SuccessfullytransferredTestTokens": "Тестовые токены успешно отправлены",

        "TestSENTunit" : "TestSENT",
        "TestETHunit" : "TestETH",
        "ClaimedBy" : "Tokens Claimed by Service Provider",
        "AddressToSend":"ADDRESS TO SEND",
        "NodeID" : "Node ID",
        "Socks5ComingSoon" : "Socks5 (Coming Soon)",
        "PrivateComingSoon" : "Private (Coming Soon)",
        "VersionInSidebar":"dVPN - alpha-0.1.01",
    },

    zh: {
        'History': '历史记录',
        'EthTransactions': 'ETH交易',
        'SentTransactions': 'SENT 交易',
        'NoTransactions': '未有交易记录',
        'Send': '发送',
        'To': '到',
        'SendTo': '发送到以下地址',
        'AmountTo': '发送数量',
        'TokenBal': '代币余额',
        'Convert': '转换',
        'ConvertERC': '把ERC20转换为SENT',
        'ExchangeERC': '将ERC20代币兑换为SENT代币',
        'From': '从',
        'Amount': '数量',
        'GasLimit': '燃料限值',
        'Password': '密码',
        'GasPrice': '燃料价格',
        'Next': '下一步',
        'Back': '返回',
        'Out': '转出',
        'In': '转入',
        'Status': '状态',
        'Success': '成功',
        'Fail': '失败',
        'Copy': '复制',
        'City': '城市',
        'Country': '国家',
        'Due': '额度',
        'Copied': '已成功复制到粘贴板',
        'Receive': '接收',
        'GetTokens': '获得免费代币',
        'VpnList': 'VPN列表',
        'SelectNode': '选择任一节点进行连接',
        'CheckInternet': '检查您的网络连接',
        'NoVPN': '没有连接到VPN',
        'VpnHistory': 'VPN历史记录',
        "TransactionsHistory": "交易历史记录",
        'TotalDue': '总额',
        'TotalDuration': '总时长',
        'TotalData': '总接收数据',
        'SessionId': '会话ID',
        'Sessions': '会话',
        'VpnAddress': 'VPN地址',
        'Bandwidth': '带宽',
        'Latency': '延时',
        'Loading': '正在加载...',
        'Speed': '速度',
        'Location': '地点',
        'Duration': '时长',
        'DownloadUsage': '下载使用',
        'UploadUsage': '上传使用',
        'Disconnect': '断开连接',
        'DisconnectVPN': '已断开VPN',
        'ConnectedVPN': '已连接VPN',
        'Disconnecting': '正在断开连接...',
        'Connecting': '正在连接...请等待',
        'ClickPay': '点击支付',
        'ReceivedData': '已接收数据',
        'SearchCity': '搜索城市或国家',
        'Time': '时间',
        'NoServers': '目前没有VPN服务器可供使用',
        'PayNow': '马上支付',
        'AlreadyReport': '已经支付了？提交报告',
        'List': '列表',
        'VPNDetails': 'VPN 详细信息',
        'ClickVPN': '点击任一节点连接到VPN',
        'KeystoreLogin': '输入密钥库密码登录',
        'KeyPass': '输入密钥库密码',
        'CheckCre': '正在检查证书...',
        'Map': '地图',
        'Pay': '支付',
        'Flag': '国旗',
        'Uhave': '您拥有',
        'Close': '关闭',
        'Cancel': '取消',
        'Connect': '连接',
        'Submit': '提交',
        'TestMode': '测试模式已激活',
        'AnonymousVPN': '由区块链保障安全性的匿名VPN',
        'OpenSource': '开源钱包和安全服务平台',
        'CreateRestore': '创建/恢复钱包',
        'SentinelAnonymity': 'Sentinel匿名平台',
        'PeerToPeer': '适用于多链的点对点基于ERC隐私应用程序套件，提供无燃料费用服务及匿名ERC代币交易',
        'BetaVersion': '带有测试网络的测试版0.1.0',
        'InitialPayment': '初始付款提醒',
        'InorderVPN': '为了使用VPN，首次需要先支付100 SENT。请支付，然后尝试连接到VPN',
        'CreateAUID': '创建您的匿名用户ID',
        'CreateTooltip': '输入密码并创建您专属的Sentinel匿名用户ID（AUID）',
        'PasswordAUID': '输入密码以创建AUID',
        'ConfirmPwd': '确认密码',
        'Create': '创建',
        'SelectKeystore': '选择密钥库文件',
        'RestoreKeystore': '恢复密钥库文件',
        'DidNotMatch': '密码与确认密码不匹配',
        'KeyPassMatch': '密钥库与密码不匹配',
        'BeCareful': '请注意',
        'CopyKeys': "将密钥复制到安全的地方。请记住，我们不会将任何密钥存储在我们的数据库中。我们不会保留该数据库。",
        'YourAddress': '您的地址',
        'PrivateKey': '私钥',
        'KeyLocation': '您的密钥库文件被存储到',
        'YesUnderstand': '是的，我明白，我已经把我的密钥复制到安全的地方',
        'GoToDash': '转到仪表板',
        'AmountEmpty': '未输入数量',
        'PasswordEmpty': '未输入密码',
        'ToTooltip': '要将Sentinel代币发送到的钱包地址',
        'AmountTool1': '要发送的以太坊/Sentinel代币的总数',
        'AmountTool2': '是的，该钱包也可以持有以太坊。',
        'GasFieldTool': '21000是默认的燃料限值',
        'GasPriceTool': '您为每单位支付的燃料数量',
        'PasswordTool': '您的Sentinel AUID密码',
        'Price': '价格 (SENTS/GB)',
        'Cost': '费用',

        'WalletTM': 'TENDERMINT',
        'WalletERC': 'ERC20',
        'TSent': 'TSENT',
        'TestNet': '测试网',
        'WalletAddress': '钱包地址',
        'ERC20WalletCopy': '复制ERC20 Sent钱包地址',
        'TMWalletCopy': '复制Tendermint钱包地址',
        'TestSent': '测试网',
        'Sent': '已发送',
        'Eth': 'ETH',
        'TestEth': '测试ETH',
        'TestNetTM': 'TENDERMINT测试网',
        'TestNetETH': '以太坊测试网',
        'RefreshBalTM': '刷新TENDERMINT余额 ',
        'RefreshBalETH': '刷新ERC20余额 ',
        'Sending': '正在发送。。。',
        'TM': 'TENDERMINT',
        'ETH': '以太坊',
        'TxHistory': 'TX历史记录',
        'Account': '账户',
        'Transfer': '转账',
        'NoSentTx': '未有SENT交易记录',
        'NoEthTx': '未有ETH交易记录',
        'NodVPNNodes': '没有发现dVPN节点',
        'NoPrevSessions': '没有之前的会话',
        'ConnectTodVPN': '连接到dVPN',
        'ConnectingdVPN': "正在连接。。。",
        'Connected': '已连接',
        'Activated': '已激活',
        'TMTestNet': 'Tendermint测试网',
        'ETHTestNet': '以太坊测试网',
        'ETHMainNet': '以太坊主网',
        'Offline': '您目前是离线状态',
        "OpenVPN": "OpenVPN",
        'Socks5': "SOCKS5",
        'Failed': '失败',
        'Sents': ' SENTS',
        'Secs': ' 秒',
        'MS': " ms",
        'Mbps': ' Mbps',
        'SentPerGb': ' SENT/GB',
        'TSentLocked': '已锁定的TSENT',
        'TSentConsumed': '已消费的TSENT',
        'Note': '注意：您的帐户余额为0 TSENT。您可以免费获得一些 TSENT，请点击上面的“获得代币”。',
        'TxFailed': '交易失败',
        'IncorrectPwd': '密码错误',
        'TxSuccess': '已成功交易',
        'VpnConnected': '已连接VPN',
        'WentWrong': '发生了一些错误',
        'EnterTxHash': "输入交易的txhash",
        'ErrOccured': '发生错误',


        'Algorithm': '算法',
        'Version': '版本',
        'Rating': '评价',
        'Public': '公共',
        'Private': '私人',
        'Selected': '已选择',
        'OpenVPNList': 'OpenVPN列表',
        'GWEI': ' GWEI',
        'Eths': ' ETHS',
        "Refresh": "刷新",
        "Sentinel": "SENTINEL",

        "SearchdVPNnode": "搜索dVPN节点",
        "SwitchPrivate": "切换到私人网络",
        "EnterAuthCode": "请输入您的授权码以连接到私人网络",
        "AuthCode": "授权码",
        "ToggleMenu": "切换菜单",
        "WindowTitle": "Sentinel Network - dVPN - alpha-0.1.0",
        "RunInBackground": "在后台运行",
        "Confirm": "确认",
        "CurrentlyConnectedToVPN": "您目前已连接VPN",
        "DisconnectOpenVPN": "断开连接OpenVPN",
        "Edit": "编辑",
        "Undo": "撤销",
        "Redo": "恢复",
        "Cut": "切断",
        "Paste": "粘贴",
        "SelectAll": "选择所有",
        "Quit": "退出",
        "ToggleDevTools": "切换开发者工具",
        "IPAddress": "IP地址",
        "Upload": "上传",
        "Download": "下载",
        "RateSession": "评价该会话",
        "Comment": "意见",
        "RatedSuccess": "已成功评价",
        "ConnectedToVPN": "已连接到VPN",


        "MessageSuccess": "这是一条成功消息！",
        "MessageErr": "这是一条错误消息！",
        "MessageWarn": "这是一条警告消息！",
        "MessageInfo": "这是一条信息消息！",
        "CheckStatus": "检查状态",
        "OR": "（或）",
        "CreateWalletSST": "在Sentinel Tendermint TestNet (STT) #1上创建一个钱包",
        "AccountName": "账户名称",
        "AccountPwd": "账户密码",
        "CreateAccount": "创建账户",
        "MB": "MB",
        "OfflineInFooter": "离线",
        "TxID": "TxID",
        "SentGroup": "SentinelGroup.io",
        "SwapOnPIVX": "互换PIVX代币",
        "EnterRefundAddr": "输入退款地址",
        "EnterPIVXAddr": "输入pivx地址",
        "Example": "示例",
        "KeyStorePwd": "密钥库密码",
        "PIVXTokensto": "PIVX代币到 ",
        "Swap": "互换",
        "Swaping": "正在互换",
        "Total": "总数",
        "TokensToBeSwapped": "要互换的代币",
        "Enter": "输入",
        "RefundAddr": "退款地址",
        "PIVXAddr": "PIVX地址",
        "Expected": "预期的",
        "Tokens": " 代币",
        "Sentinel[SENT]": "Sentinel [SENT]",
        "NoTokens": "没有发现代币",
        "Address": "地址",
        "PubKey": "公钥",
        "Seed": "种子",
        "GoToSTWallet": "去到Sentinel Terdermint钱包",
        "NoVPNUsed": "没有使用过的VPN",
        "ProblemEnablingPrivateNet": "启用私人网络时发生问题",
        "PrivateNetEnabledWith": "私人网络已启用 ",
        "SentTokens": "SENT代币",
        "Balance": "余额",
        "Converting": "C正在兑换",
        "OpenVpnNotInstalled": "没有安装OpenVPN。请去往",
        "PleaseGo": "请去往",
        "OpenVpnPath": "C:\\Users\\(您的用户名\\AppData\\Local\\Sentinel\\app-0.1.0\\resources\\extras",
        "OpenVpnInstallCmd": "然后运行openvpn-install-2.3.18-I602-x86_64.exe",
        "OpenVpnMessage": "只需安装Openvpn而无需更改安装目录。",
        "YourUserName": "您的用户名称",
        "AndRun": "然后运行",
        "OpenVpnInstallAlert": "没有安装OpenVPN。请去往 C:\\Users\\(您的用户名\\AppData\\Local\\Sentinel\\app-0.1.0\\resources\\extras 然后运行 openvpn-install-2.3.18-I602-x86_64.exe。 只需安装Openvpn而无需更改安装目录。",
        "ConnectedSocks": "已链接到Socks",


        "Can'tdetectcurrentosplatform.": "无法检测当前的os平台。",
        "ConnectingVPNFailed.PleaseTryAgain": "连接VPN失败。请再试一次",
        "Unabletoreachsentinelserveratthismoment": "此时无法访问Sentinel服务器",
        "Currentlyserverhassomenetworkissues.Pleasetryotherserver.": "当前服务器有一些网络问题。请尝试其它服务器。",
        "Somethingwentwrong.PleaseTryAgain": "出错了。请再试一次",
        "Erroroccuredwhileinstallingbrew": "安装brew时发生错误",
        "PackageBrewisnotInstalled": "未安装Brew安装包",
        "Erroroccuredwhileinstallingopenvpn": "安装openvpn时发生错误",
        "Erroroccuredwhileinstallingpidof": "安装pidof时发生错误",
        "Erroroccuredwhileinstallingshadowsocks-libev": "安装shadowsocks-libev时发生错误",
        "ErroroccurredwhilegettingSOCKS5credentials": "获取SOCKS5证书时发生错误",
        "Erroroccurredwhileinitiatingtransferamount.": "发起交易金额时发生错误",
        "Erroroccurredwhilegettingtransactionhistory.": "获取交易历史记录时发生错误",
        "Erroroccuredwhilesubmittingrating": "提交评价时发生错误",
        "Somethingwentwrong": "出错了",
        "InternalServerError": "内部服务器错误",
        "Oops..!Youhavecrossedthetokenlimit": "哎呀..！ 您已越过代币限制",
        "Somethingwentwrongwhilegettingtokens": "获取代币时出错了",
        "Problemfacedinreporting.Tryagainlater": "提交报告时出现问题。请稍后再试",
        "NotransactionfoundwiththattransactionId": "找不到该交易ID的交易",
        "Notavalidtransactionhash": "不是有效的交易哈希",
        "ReportedSuccessfully": "已成功提交报告",
        "TransactionFailed": "交易失败",
        "TransactionSuccess": "交易成功",
        "Successfullysent150TSENT": "成功发送150 TSENT",
        "Successfullysent100TSENT": "成功发送100 TSENT",
        "InitialPaymentAlert": "初始付款提示",
        "PleaseClickPay": "请点击支付按钮进行初始付款",
        "UsedAllLocked": "您已使用所有锁定的TSENT。请重新连接并支付。",
        "Disconnectingfailed": "断开连接失败",

        "Erroroccurredwhileinitiatingthetransaction.": "发起交易时发生错误",
        "CurrentlyVPNserverisnotavailable.Pleasetryaftersometime.": "当前VPN服务器不可用。 请稍后再试。",
        "StartedVPNsession.": "开始了一个VPN会话。",
        "ConnectiontimedoutwhileconnectingtoVPNserver.": "连接到VPN服务器时连接超时。",
        "InitialVPNpaymentisnotdone.": "初始VPN付款尚未完成",
        "Erroroccurredwhilechekinginitialpaymentstatus.": "检查初始付款状态时发生错误",
        "Erroroccurredwhilecheckingdueamount.": "检查金额数量时发生错误",
        "Yourbalanceislessthan100SENTs.": "您的余额少于100 SENT",
        "Wrongclientwalletaddressortoken.": "错误的客户端钱包地址或代币。",
        "YouHaveDue": "您有应付金额，请付清费用后再尝试。",


        "TestTokensalreadyclaimed": "测试令牌已经声称",
        "Erroroccurredwhiletransferringfreeamount.": "转移免费金额时出错。",
        "SuccessfullytransferredTestTokens": "成功转移了测试令牌",

        "TestSENTunit" : "TestSENT",
        "TestETHunit" : "TestETH",
        "ClaimedBy" : "服务提供商声称的令牌",
        "AddressToSend":"ADDRESS TO SEND",
        "NodeID" : "Node ID",
        "Socks5ComingSoon" : "Socks5 (Coming Soon)",
        "PrivateComingSoon" : "Private (Coming Soon)",
        "VersionInSidebar":"dVPN - alpha-0.1.01",

    },
}

module.exports = lang;