let lang = {
    zh: {
        'History': '历史记录',
        'EthTransactions': 'ETH交易',
        'SentTransactions': 'SENT 交易',
        'NoTransactions': '未有交易记录',
        'Send': '发送',
        'To': '到',
        'SendTo': '发送到以下地址',
        'AmountTo': '发送数量',
        'TokenBal': '代币余额',
        'Convert': '转换',
        'ConvertERC': '把ERC20转换为SENT',
        'ExchangeERC': '将ERC20代币兑换为SENT代币',
        'From': '从',
        'Amount': '数量',
        'GasLimit': '燃料限值',
        'Password': '密码',
        'GasPrice': '燃料价格',
        'Next': '下一步',
        'Back': '返回',
        'Out': '转出',
        'In': '转入',
        'Status': '状态',
        'Success': '成功',
        'Fail': '失败',
        'Copy': '复制',
        'City': '城市',
        'Country': '国家',
        'Due': '额度',
        'Copied': '已成功复制到粘贴板',
        'Receive': '接收',
        'GetTokens': '获得免费代币',
        'VpnList': 'VPN列表',
        'SelectNode': '选择任一节点进行连接',
        'CheckInternet': '检查您的网络连接',
        'NoVPN': '没有连接到VPN',
        'VpnHistory': 'VPN历史记录',
        "TransactionsHistory": "交易历史记录",
        'TotalDue': '总额',
        'TotalDuration': '总时长',
        'TotalData': '总接收数据',
        'SessionId': '会话ID',
        'Sessions': '会话',
        'VpnAddress': 'VPN地址',
        'Bandwidth': '带宽',
        'Latency': '延时',
        'Loading': '正在加载...',
        'Speed': '速度',
        'Location': '地点',
        'Duration': '时长',
        'DownloadUsage': '下载使用',
        'UploadUsage': '上传使用',
        'Disconnect': '断开连接',
        'DisconnectVPN': '已断开VPN',
        'ConnectedVPN': '已连接VPN',
        'Disconnecting': '正在断开连接...',
        'Connecting': '正在连接...请等待',
        'ClickPay': '点击支付',
        'ReceivedData': '已接收数据',
        'SearchCity': '搜索城市或国家',
        'Time': '时间',
        'NoServers': '目前没有VPN服务器可供使用',
        'PayNow': '马上支付',
        'AlreadyReport': '已经支付了？提交报告',
        'List': '列表',
        'VPNDetails': 'VPN 详细信息',
        'ClickVPN': '点击任一节点连接到VPN',
        'KeystoreLogin': '输入密钥库密码登录',
        'KeyPass': '输入密钥库密码',
        'CheckCre': '正在检查证书...',
        'Map': '地图',
        'Pay': '支付',
        'Flag': '国旗',
        'Uhave': '您拥有',
        'Close': '关闭',
        'Cancel': '取消',
        'Connect': '连接',
        'Submit': '提交',
        'TestMode': '测试模式已激活',
        'AnonymousVPN': '由区块链保障安全性的匿名VPN',
        'OpenSource': '开源钱包和安全服务平台',
        'CreateRestore': '创建/恢复钱包',
        'SentinelAnonymity': 'Sentinel匿名平台',
        'PeerToPeer': '适用于多链的点对点基于ERC隐私应用程序套件，提供无燃料费用服务及匿名ERC代币交易',
        'BetaVersion': '带有测试网络的测试版0.1.01',
        'InitialPayment': '初始付款提醒',
        'InorderVPN': '为了使用VPN，首次需要先支付100 SENT。请支付，然后尝试连接到VPN',
        'CreateAUID': '创建您的匿名用户ID',
        'CreateTooltip': '输入密码并创建您专属的Sentinel匿名用户ID（AUID）',
        'PasswordAUID': '输入密码以创建AUID',
        'ConfirmPwd': '确认密码',
        'Create': '创建',
        'SelectKeystore': '选择密钥库文件',
        'RestoreKeystore': '恢复密钥库文件',
        'DidNotMatch': '密码与确认密码不匹配',
        'KeyPassMatch': '密钥库与密码不匹配',
        'BeCareful': '请注意',
        'CopyKeys': "将密钥复制到安全的地方。请记住，我们不会将任何密钥存储在我们的数据库中。我们不会保留该数据库。",
        'YourAddress': '您的地址',
        'PrivateKey': '私钥',
        'KeyLocation': '您的密钥库文件被存储到',
        'YesUnderstand': '是的，我明白，我已经把我的密钥复制到安全的地方',
        'GoToDash': '转到仪表板',
        'AmountEmpty': '未输入数量',
        'PasswordEmpty': '未输入密码',
        'ToTooltip': '要将Sentinel代币发送到的钱包地址',
        'AmountTool1': '要发送的以太坊/Sentinel代币的总数',
        'AmountTool2': '是的，该钱包也可以持有以太坊。',
        'GasFieldTool': '21000是默认的燃料限值',
        'GasPriceTool': '您为每单位支付的燃料数量',
        'PasswordTool': '您的Sentinel AUID密码',
        'Price': '价格 (SENTS/GB)',
        'Cost': '费用',

        'WalletTM': 'TENDERMINT',
        'WalletERC': 'ERC20',
        'TSent': 'TSENT',
        'TestNet': '测试网',
        'WalletAddress': '钱包地址',
        'ERC20WalletCopy': '复制ERC20 Sent钱包地址',
        'TMWalletCopy': '复制Tendermint钱包地址',
        'TestSent': '测试网',
        'Sent': '已发送',
        'Eth': 'ETH',
        'TestEth': '测试ETH',
        'TestNetTM': 'TENDERMINT测试网',
        'TestNetETH': '以太坊测试网',
        'RefreshBalTM': '刷新TENDERMINT余额 ',
        'RefreshBalETH': '刷新ERC20余额 ',
        'Sending': '正在发送。。。',
        'TM': 'TENDERMINT',
        'ETH': '以太坊',
        'TxHistory': 'TX历史记录',
        'Account': 'ACCOUNT',
        'Transfer': '转账',
        'NoSentTx': '未有SENT交易记录',
        'NoEthTx': '未有ETH交易记录',
        'NodVPNNodes': '没有发现dVPN节点',
        'NoPrevSessions': '没有之前的会话',
        'ConnectTodVPN': '连接到dVPN',
        'ConnectingdVPN': "正在连接。。。",
        'Connected': '已连接',
        'Activated': '已激活',
        'TMTestNet': 'Tendermint测试网',
        'ETHTestNet': '以太坊测试网',
        'ETHMainNet': '以太坊主网',
        'Offline': '您目前是离线状态',
        "OpenVPN": "OpenVPN",
        'Socks5': "SOCKS5",
        'Failed': '失败',
        'Sents': 'SENTS',
        'Secs': '秒',
        'MS': "ms",
        'Mbps': ' Mbps',
        'SentPerGb': ' SENT/GB',
        'TSentLocked': '已锁定的TSENT',
        'TSentConsumed': '已消费的TSENT',
        'Note': '注意：您的帐户余额为0 TSENT。您可以免费获得300 TSENT，请点击上面的“获得代币”。',
        'TxFailed': '交易失败',
        'IncorrectPwd': '密码错误',
        'TxSuccess': '已成功交易',
        'VpnConnected': '已连接VPN',
        'WentWrong': '发生了一些错误',
        'EnterTxHash': "输入交易的txhash",
        'ErrOccured': '发生错误',


        'Algorithm': '算法',
        'Version': '版本',
        'Rating': '评价',
        'Public': '公共',
        'Private': '私人',
        'Selected': '已选择',
        'OpenVPNList': 'OpenVPN列表',
        'GWEI': 'GWEI',
        'Eths': 'ETHS',
        "Refresh": "刷新",
        "Sentinel": "SENTINEL",

        "SearchdVPNnode": "搜索dVPN节点",
        "SwitchPrivate": "切换到私人网络",
        "EnterAuthCode": "请输入您的授权码以连接到私人网络",
        "AuthCode": "授权码",
        "ToggleMenu": "切换菜单",
        "WindowTitle": "Sentinel Network - dVPN - alpha-0.1.0",
        "RunInBackground": "在后台运行",
        "Confirm": "确认",
        "CurrentlyConnectedToVPN": "您目前已连接VPN",
        "DisconnectOpenVPN": "断开连接OpenVPN",
        "Edit": "编辑",
        "Undo": "撤销",
        "Redo": "恢复",
        "Cut": "切断",
        "Copy": "复制",
        "Paste": "粘贴",
        "SelectAll": "选择所有",
        "Quit": "退出",
        "ToggleDevTools": "切换开发者工具",
        "IPAddress": "IP地址",
        "Upload": "上传",
        "Download": "下载",
        "RateSession": "评价该会话",
        "Comment": "意见",
        "RatedSuccess": "已成功评价",
        "ConnectedToVPN": "已连接到VPN",


        "MessageSuccess": "This is a success message!",
        "MessageErr": "This is an error message!",
        "MessageWarn": "This is a warning message!",
        "MessageInfo": "This is an information message!",
        "CheckStatus": "Check Status",
        "OR": "(OR)",
        "CreateWalletSST": "Create a Wallet on Sentinel Tendermint TestNet (STT) #1",
        "AccountName": "Account Name",
        "AccountPwd": "Account Password",
        "CreateAccount": "Create Account",
        "MB": "MB",
        "OfflineInFooter": "Offline",
        "TxID": "TxID",
        "SentGroup": "SentinelGroup.io",
        "SwapOnPIVX": "Swap on PIVX Tokens",
        "EnterRefundAddr": "Enter refund address",
        "EnterPIVXAddr": "Enter pivx address",
        "Example": "Example",
        "KeyStorePwd": "KEYSTORE PASSWORD",
        "PIVXTokensto": "PIVX Tokens to ",
        "Swap": "SWAP",
        "Swaping": "SWAPING",
        "Total": "Total",
        "TokensToBeSwapped": "tokens to be swapped",
        "Enter": "Enter",
        "RefundAddr": "refund Address",
        "PIVXAddr": "PIVX Address",
        "Expected": "Expected",
        "Tokens": " Tokens",
        "Sentinel[SENT]": "Sentinel [SENT]",
        "NoTokens": "No Tokens Found",
        "Address": "Address",
        "PubKey": "Public Key",
        "Seed": "Seed",
        "GoToSTWallet": "Go To Sentinel Tendermint Wallet",
        "NoVPNUsed": "No VPN Used",
        "ProblemEnablingPrivateNet": "Problem in enabling private net",
        "PrivateNetEnabledWith": "Private Net is Enabled with ",
        "SentTokens": "SENT TOKENS",
        "Balance": "Balance",
        "Converting": "CONVERTING",
        "OpenVpnNotInstalled": "OpenVPN Not Installed.",
        "PleaseGo": "Please go to",
        "OpenVpnPath": "C:\Users(your-user-name)\AppData\Local\Sentinel\app-0.1.01\resources\extras",
        "OpenVpnInstallCmd": "and run openvpn-install-2.3.18-I602-x86_64.exe.",
        "OpenVpnMessage": "Just Install Openvpn without changing installation directory.",
        "YourUserName": "your-user-name",
        "AndRun": "and run",
        "OpenVpnInstallAlert": "OpenVPN Not Installed. Please go to C:\Users(your-user-name)\AppData\Local\Sentinel\app-0.1.01\resources\extras and run openvpn-install-2.3.18-I602-x86_64.exe. Just Install Openvpn without changing installation directory.",
        "ConnectedSocks":"Connected to Socks"
    },
}

module.exports = lang;