let lang = {
    en: {
        'History': 'HISTORY',
        'EthTransactions': 'Eth Transactions',
        'SentTransactions': 'Sent Transactions',
        'NoTransactions': 'No Transactions Yet',
        'Send': 'SEND',
        'To': 'To',
        'From': 'From',
        'Amount': 'Amount',
        'GasLimit': 'Gas Limit',
        'Password': 'Password',
        'GasPrice': 'Gas Price',
        'Next': 'NEXT',
        'Back': 'BACK',
        'Out': 'OUT',
        'In': 'IN',
        'Status': 'Status',
        'Success': 'Success',
        'Fail': 'Fail',
        'Copy': 'Copy',
        'Copied': 'Copied to Clipboard Successfully',
        'Receive': 'RECEIVE',
        'GetTokens': 'GET FREE TOKENS',
        'VpnList': 'VPN LIST',
        'NoVPN': 'No VPN Connected',
        'VpnHistory': 'VPN HISTORY',
        'TotalDue': 'Total Due',
        'TotalDuration': 'Total Duration',
        'TotalData': 'Total Received Data',
        'SessionId': 'Session ID',
        'Sessions': 'Sessions',
        'VpnAddress': 'VPN address',
        'Bandwidth':'Bandwidth',
        'Latency':'Latency',
        'Duration': 'Duration',
        'Disconnect':'Disconnect',
        'ReceivedData': 'Received Data',
        'Time': 'Time',
        'NoServers':'Currently, no VPN servers are available',
        'PayNow': 'Pay Now',
        'AlreadyReport': 'Already Paid? Report',
        'List': 'LIST',
        'ClickVPN':'Click any node to connect to VPN',
        'Map': 'MAP',
        'Pay':'Pay',
        'Close':'Close',
        'Cancel': 'CANCEL',
        'Connect': 'CONNECT',
        'TestMode': 'TEST MODE ACTIVATED'
    },
    ja: {
        'History': '歴史',
        'EthTransactions': 'Eth トランザクション',
        'NoTransactions': 'トランザクションがまだありません。',
        'SentTransactions': 'Sent トランザクション',
        'Send': '送信',
        'To': '宛先',
        'From': 'から',
        'Amount': '量',
        'GasLimit': 'Gas リミット',
        'Password': 'パスワード',
        'GasPrice': 'Gas 価格',
        'Next': '次に',
        'Back': '戻る',
        'Out': 'アウト',
        'In': 'に',
        'Status': 'ステータス',
        'Success': '成功',
        'Fail': '失敗します',
        'Copy': 'コピー',
        'Copied': 'クリップボードに正常にコピーされました',
        'Receive': '受信',
        'GetTokens': '無料トークンを入手',
        'VpnList': 'VPN リスト',
        'NoVPN': 'VPN接続なありません',
        'VpnHistory': 'VPN 歴史',
        'TotalDue': '合計支払額',
        'TotalDuration': '合計期間',
        'TotalData': '合計受信データ',
        'SessionId': 'セッション ID',
        'Sessions': 'セッション',
        'VpnAddress': 'VPN アドレス',
        'Duration': '期間',
        'ReceivedData': '受信データ',
        'Bandwidth':'帯域幅',
        'Latency':'待ち時間',
        'NoServers':'現在、利用可能なVPNサーバーはありません',
        'Time': '時間',
        'PayNow': '現在有料',
        'Disconnect':'ディスコネクト',
        'AlreadyReport': '既に支払われたか。レポート',
        'List': 'リスト',
        'Map':'地図',
        'Pay':'支払う',
        'ClickVPN':'任意のノードをクリックしてVPNに接続します。',
        'Close':'閉じる',
        'Cancel': 'キャンセル',
        'Connect': 'コネクト',
        'TestMode': 'テストモードが活性化'
    }
}

module.exports = lang;