let lang = {
    en: {
        'History': 'HISTORY',
        'EthTransactions': 'Eth Transactions',
        'SentTransactions': 'Sent Transactions',
        'NoTransactions': 'No Transactions Yet',
        'Send': 'SEND',
        'To': 'To',
        'From': 'From',
        'Amount': 'Amount',
        'GasLimit': 'Gas Limit',
        'Password': 'Password',
        'GasPrice': 'Gas Price',
        'Next': 'NEXT',
        'Back': 'BACK',
        'Out': 'OUT',
        'In': 'IN',
        'Status': 'Status',
        'Success': 'Success',
        'Fail': 'Fail',
        'Copy': 'Copy',
        'City': 'City',
        'Country': 'Country',
        'Due': 'Due',
        'Copied': 'Copied to Clipboard Successfully',
        'Receive': 'RECEIVE',
        'GetTokens': 'GET FREE TOKENS',
        'VpnList': 'VPN LIST',
        'SelectNode': 'Select any node to connect',
        'CheckInternet': 'Check your internet connection',
        'NoVPN': 'No VPN Connected',
        'VpnHistory': 'VPN HISTORY',
        'TotalDue': 'Total Due',
        'TotalDuration': 'Total Duration',
        'TotalData': 'Total Received Data',
        'SessionId': 'Session ID',
        'Sessions': 'Sessions',
        'VpnAddress': 'VPN address',
        'Bandwidth': 'Bandwidth',
        'Latency': 'Latency',
        'Loading': 'Loading...',
        'Speed': 'Speed',
        'Location': 'Location',
        'Duration': 'Duration',
        'DownloadUsage': 'Download Usage',
        'UploadUsage': 'Upload Usage',
        'Disconnect': 'Disconnect',
        'DisconnectVPN': 'Disconnected VPN',
        'ConnectedVPN': 'Connected VPN',
        'Disconnecting': 'Disconnecting...',
        'Connecting': 'Connecting...Please Wait',
        'ClickPay': 'Click to Pay',
        'ReceivedData': 'Received Data',
        'SearchCity': 'Search City or Country',
        'Time': 'Time',
        'NoServers': 'Currently, no VPN servers are available',
        'PayNow': 'Pay Now',
        'AlreadyReport': 'Already Paid? Report',
        'List': 'LIST',
        'VPNDetails': 'VPN Details',
        'ClickVPN': 'Click any node to connect to VPN',
        'KeystoreLogin': 'Enter Keystore Password to Login',
        'KeyPass': 'Enter keystore password',
        'CheckCre': 'Checking Credentials...',
        'Map': 'MAP',
        'Pay': 'Pay',
        'Flag': 'Flag',
        'Uhave': 'You have',
        'Close': 'Close',
        'Cancel': 'CANCEL',
        'Connect': 'CONNECT',
        'Submit': 'Submit',
        'TestMode': 'TEST MODE ACTIVATED',
        'AnonymousVPN': 'Anonymous VPN backed by blockchain security',
        'OpenSource': 'Open-source wallet and secure service platform',
        'CreateRestore': 'Create / Restore Wallet',
        'SentinelAnonymity': 'Sentinel Anonymity Platform',
        'PeerToPeer': 'Peer to peer erc based privacy application suite with multi chain for gas-free services and anonymous erc token transactions',
        'BetaVersion': 'Beta Version 0.0.4 with testnet',
        'InitialPayment': 'Initial Payment Reminder',
        'InorderVPN': 'Inorder to use VPN, you need to pay 100 sents for the first time. Please pay and then try to connect to the vpn.',
        'CreateAUID': 'Create your Anonymous User ID',
        'CreateTooltip': 'Enter a password and create your own Sentinel Anonymous User ID (AUID)',
        'PasswordAUID': 'Enter Password to create AUID',
        'ConfirmPwd': 'Confirm Password',
        'Create': 'Create',
        'SelectKeystore': 'Select keystore file',
        'RestoreKeystore': 'Restore Keystore File',
        'DidNotMatch': 'Password and Confirm Password did not match',
        'KeyPassMatch': 'Keystore and Password does not match',
        'BeCareful': 'Be Careful',
        'CopyKeys': "Copy your keys to some secured place. Remember we don't store any of your keys in ours databases.We don't maintain a database.",
        'YourAddress': 'Your Address',
        'PrivateKey': 'Private Key',
        'KeyLocation': 'Your keystore file is stored at',
        'YesUnderstand': 'Yes, I understood, I copied my keys in secured place',
        'GoToDash': 'Go to Dashboard',
        'AmountEmpty': 'Amount field is Empty',
        'PasswordEmpty': 'Password field is Empty',
        'ToTooltip':'Wallet Address that you want to send Sentinel Tokens to',
        'AmountTool1':'Total Ethereum/Sentinel Tokens that you want to send to.',
        'AmountTool2':'Yes, this wallet can hold Ethereum too.',
        'GasFieldTool':'21000 is the default gas limit',
        'GasPriceTool':'Amount you pay per unit of gas',
        'PasswordTool':'Your Sentinel AUID Password',
        'Price':'Price (SENTS/GB)',
        'Cost':'Price'
    },
    ja: {
        'BeCareful': 'ご注意',
        'ToTooltip':'あなたがセンチネルトークンを送信したいウォレット住所',
        'AmountTool1':'送信したいEthereum / Sentinelトークンの合計。',
        'AmountTool2':'はい、この財布にはエテリアムも収納できます',
        'GasFieldTool':'デフォルトのガス制限は21000です',
        'GasPriceTool':'ガスの単位あたりのあなたが支払う金額',
        'PasswordTool':'あなたのSentinel AUIDパスワード',
        'Price':'価格 (SENTS/GB)',
        'Cost':'価格',
        'CopyKeys': '安全な場所にあなたの秘密鍵を書き写してください。私達はデータベースにあなたの秘密鍵を格納しないことを忘れないでください。 私達はデータベースを保持しません。 ',
        'YourAddress': 'あなたのアドレス',
        'PrivateKey': '秘密鍵',
        'KeyLocation': 'キーストアファイルの格納場所',
        'YesUnderstand': 'はい、私は理解しました。安全な場所に秘密鍵を保管しました。',
        'GoToDash': 'ダッシュボードへ行く',
        'AmountEmpty': '金額欄が空です',
        'PasswordEmpty': 'パスワードフィールドが空です',
        'AnonymousVPN': 'ブロックチェーンのセキュリティに基づく匿名VPN',
        'OpenSource': 'オープンソースウォレットと安全なサービスプラットフォーム',
        'CreateRestore': 'ウォレット作成／復元',
        'SentinelAnonymity': 'センチネルプラットフォーム',
        'PeerToPeer': 'フリーサービスと匿名ERCトークン取引のマルチチェーン付属のピアツーピアERCベースのプライバシーアプリケーション',
        'BetaVersion': '0.0.4のベータ版',
        'InitialPayment': '最初の支払リマインダ',
        'InorderVPN': 'VPNを使用するために最初に100SENTを支払う必要があります。支払いしてVPNに接続してください。',
        'CreateAUID': 'あなたの匿名ユーザーIDを作成する',
        'CreateTooltip': 'パスワードを入力し、独自のSentinel匿名ユーザーID（AUID）を作成します。',
        'PasswordAUID': 'AUIDを作成するためのパスワードを入力してください',
        'ConfirmPwd': 'パスワードを認証する',
        'SelectKeystore': 'キーストアファイルを選択する',
        'RestoreKeystore': 'キーストア ファイルを復元します。',
        'DidNotMatch': 'パスワードとパスワードの確認が一致しませんでした',
        'KeyPassMatch': 'キーストアとパスワードが一致しません',
        'Create': '作成する',
        'History': '歴史',
        'EthTransactions': 'Eth トランザクション',
        'NoTransactions': 'トランザクションがまだありません。',
        'SentTransactions': 'Sent トランザクション',
        'Send': '送信',
        'To': '宛先',
        'From': 'から',
        'Amount': '量',
        'GasLimit': 'Gas リミット',
        'Password': 'パスワード',
        'GasPrice': 'Gas 価格',
        'Next': '次に',
        'Back': '戻る',
        'Out': 'アウト',
        'In': 'に',
        'Status': 'ステータス',
        'Success': '成功',
        'Fail': '失敗します',
        'Copy': 'コピー',
        'City': 'シティ',
        'Country': '国',
        'Due': '支払額',
        'Copied': 'クリップボードに正常にコピーされました',
        'Receive': '受信',
        'GetTokens': '無料トークンを入手',
        'VpnList': 'VPN リスト',
        'NoVPN': 'VPN接続なありません',
        'VpnHistory': 'VPN 歴史',
        'TotalDue': '合計支払額',
        'TotalDuration': '合計期間',
        'TotalData': '合計受信データ',
        'SessionId': 'セッション ID',
        'Sessions': 'セッション',
        'VpnAddress': 'VPN アドレス',
        'Duration': '期間',
        'ReceivedData': '受信データ',
        'Bandwidth': '帯域幅',
        'Latency': '待ち時間',
        'Loading': '読み込んでいます...',
        'DownloadUsage': 'ダウンロードの使用',
        'UploadUsage': 'アップロードの使用',
        'SearchCity': '都市または国を検索',
        'Flag': 'フラグ',
        'Speed': '速度',
        'KeystoreLogin': 'キーストアを入力ログインするパスワード',
        'KeyPass': 'キーストアを入力パスワード',
        'ClickPay': 'クリックして支払う',
        'Location': 'ロケーション',
        'Uhave': 'あなたが持っている',
        'NoServers': '現在、利用可能なVPNサーバーはありません',
        'Time': '時間',
        'PayNow': '現在有料',
        'SelectNode': '接続する任意のノードを選択します。',
        'CheckInternet': 'インターネット接続を確認してください',
        'Disconnect': 'ディスコネクト',
        'DisconnectVPN': '切断されたVPN',
        'Disconnecting': '切断中...',
        'Connecting': '接続中...しばらくお待ちください',
        'AlreadyReport': '既に支払われたか。レポート',
        'ConnectedVPN': '接続されたVPN',
        'List': 'リスト',
        'VPNDetails': 'VPNの詳細',
        'Map': '地図',
        'Pay': '支払う',
        'ClickVPN': '任意のノードをクリックしてVPNに接続します。',
        'Close': '閉じる',
        'Cancel': 'キャンセル',
        'Submit': '提出する',
        'CheckCre': '認証情報を確認しています',
        'Connect': 'コネクト',
        'TestMode': 'テストモードが活性化'
    }
}

module.exports = lang;