let lang = {
    en: {
        'History': 'HISTORY',
        'EthTransactions': 'Eth Transactions',
        'SentTransactions':'Sent Transactions',
        'NoTransactions': 'No Transactions Yet',
        'Send': 'SEND',
        'To': 'To',
        'Amount': 'Amount',
        'GasLimit': 'Gas Limit',
        'Password': 'Password',
        'GasPrice': 'Gas Price',
        'Next':'NEXT',
        'Back':'BACK',
        'Receive': 'RECEIVE',
        'GetTokens':'GET FREE TOKENS',
        'VpnList': 'VPN LIST',
        'NoVPN': 'No VPN Connected',
        'VpnHistory': 'VPN HISTORY',
        'TotalDue': 'Total Due',
        'TotalDuration':'Total Duration',
        'TotalData':'Total Received Data',
        'SessionId': 'Session ID',
        'Sessions':'Sessions',
        'VpnAddress': 'VPN address',
        'Duration': 'Duration',
        'ReceivedData': 'Received Data',
        'Time': 'Time',
        'PayNow': 'Pay Now',
        'AlreadyReport': 'Already Paid? Report',
        'List': 'LIST',
        'Cancel': 'CANCEL',
        'Connect': 'CONNECT',
        'TestMode':'TEST MODE ACTIVATED'
    },
    ja: {
        'History': '歴史',
        'EthTransactions': 'Eth トランザクション',
        'NoTransactions': 'トランザクションがまだありません。',
        'SentTransactions':'Sent トランザクション',
        'Send': '送信',
        'To': '宛先',
        'Amount': '量',
        'GasLimit': 'Gas リミット',
        'Password': 'パスワード',
        'GasPrice': 'Gas 価格',
        'Next':'次に',
        'Back':'戻る',
        'Receive': '受信',
        'GetTokens':'無料トークンを入手',
        'VpnList': 'VPN リスト',
        'NoVPN': 'VPN接続なありません',
        'VpnHistory': 'VPN 歴史',
        'TotalDue': '合計支払額',
        'TotalDuration':'合計期間',
        'TotalData':'合計受信データ',
        'SessionId': 'セッション ID',
        'Sessions':'セッション',
        'VpnAddress': 'VPN アドレス',
        'Duration': '期間',
        'ReceivedData': '受信データ',
        'Time': '時間',
        'PayNow': '現在有料',
        'AlreadyReport': '既に支払われたか。レポート',
        'List': 'リスト',
        'Cancel': 'キャンセル',
        'Connect': 'コネクト',
        'TestMode':'テストモードが活性化'
    }
}

module.exports = lang;