FROM alpine:3.6

ADD sentinel /root/sentinel

ADD app.py run.sh /root/

ENV SENT_ENV=DEV

RUN echo '@testing http://nl.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories && \
    echo '@community http://nl.alpinelinux.org/alpine/edge/community' >> /etc/apk/repositories && \
    apk add --no-cache geth@community ca-certificates gcc gmp-dev libffi-dev make mongodb musl-dev openssl-dev python3 python3-dev wget && \
    apk add --no-cache nano && \
    mkdir -p /data/db && \
    wget -c https://bootstrap.pypa.io/get-pip.py -O /tmp/get-pip.py && \
    python3 /tmp/get-pip.py && \
    pip3 install --no-cache-dir bitcoin ethereum==2.1.5 falcon gunicorn pprint eth_keyfile pychalk==1.0.2 pymongo uuid web3 && \
    pip3 install --no-cache-dir ipython && \
    rm -rf /tmp/* /var/tmp/* /var/cache/apk/* /var/cache/distfiles/* /root/.cache .wget-hsts

EXPOSE 8000 8545 30303 30303/udp

CMD ["sh", "/root/run.sh"]
