package com.test.openvpn;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ClientAPI_ServerEntryVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ClientAPI_ServerEntryVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ClientAPI_ServerEntryVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ovpncliJNI.delete_ClientAPI_ServerEntryVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ClientAPI_ServerEntryVector() {
    this(ovpncliJNI.new_ClientAPI_ServerEntryVector__SWIG_0(), true);
  }

  public ClientAPI_ServerEntryVector(long n) {
    this(ovpncliJNI.new_ClientAPI_ServerEntryVector__SWIG_1(n), true);
  }

  public long size() {
    return ovpncliJNI.ClientAPI_ServerEntryVector_size(swigCPtr, this);
  }

  public long capacity() {
    return ovpncliJNI.ClientAPI_ServerEntryVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    ovpncliJNI.ClientAPI_ServerEntryVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return ovpncliJNI.ClientAPI_ServerEntryVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    ovpncliJNI.ClientAPI_ServerEntryVector_clear(swigCPtr, this);
  }

  public void add(ClientAPI_ServerEntry x) {
    ovpncliJNI.ClientAPI_ServerEntryVector_add(swigCPtr, this, ClientAPI_ServerEntry.getCPtr(x), x);
  }

  public ClientAPI_ServerEntry get(int i) {
    return new ClientAPI_ServerEntry(ovpncliJNI.ClientAPI_ServerEntryVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, ClientAPI_ServerEntry val) {
    ovpncliJNI.ClientAPI_ServerEntryVector_set(swigCPtr, this, i, ClientAPI_ServerEntry.getCPtr(val), val);
  }

}
