FROM alpine:3.6

ADD sentinel /root/sentinel

ADD app.py /root/

ENV SENT_ENV=DEV

RUN echo '@testing http://nl.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories && \
    apk add --no-cache ca-certificates easy-rsa openvpn ufw@testing wget && \
    apk add --no-cache gcc musl-dev nano python-dev && \
    wget -c https://bootstrap.pypa.io/get-pip.py -O /tmp/get-pip.py && \
    python /tmp/get-pip.py && pip install --no-cache-dir requests speedtest_cli && \
    rm -rf /tmp/* /var/tmp/* /var/cache/apk/* /var/cache/distfiles/* /root/.cache .wget-hsts

EXPOSE 1194/udp

CMD ["python", "/root/app.py"]
